### ISSUE TITLE
a question about data split

### ISSUE THREAD

**Issue by Jack-bo1220** [LiheYoung/UniMatch#1]
A nice work!
Is the data split of the Cityscapes dataset used the same as that of the previous work (i,e,. ST++)? I noticed that there were many splits in the previous work. Is it the same as theirs? Thank you!

**Comment by LiheYoung** [comment]
Thanks for your interest.

We have four data partitions on the Cityscapes. The ``1/16``, ``1/8``, and ``1/4`` partitions are the same as CPS, while the ``1/30`` partition is the same as ST++, because CPS did not conduct the ``1/30`` setting.
