### ISSUE TITLE
关于cudnn加速

### ISSUE THREAD

**Issue by ql1074754250** [LiheYoung/UniMatch#10]
您好，我在本地进行训练与推理时发现，是否使用cudnn加速（torch.backends.cudnn.enabled）将带来显著差别。我注意到您的ST++代码没有设置（保持默认），而Unimatch代码则设置为True。
我想要请教的是 :
1.训练和测试是否要保证torch.backends.cudnn.enabled设置一致?（我注意到如果不一致，似乎会造成结果错误?）
2.torch.backends.cudnn.enabled的默认是?（我在官方文档中没有找到关于默认设置的描述，特向您请教）

**Comment by LiheYoung** [comment]
您好，其实我没有特地留意过这个点，只是在实现UniMatch时看到大多数codebase里会这样设置，于是也类似设置了。
