### ISSUE TITLE
关于医学图像分割场景下的结果

### ISSUE THREAD

**Issue by DINGdef** [LiheYoung/UniMatch#100]
您好，我想问一下在ACDC上的结果是验证集的最佳结果还是测试集的结果，请问测试的代码方便开源吗？

**Comment by LiheYoung** [comment]
您好，我们是合并了原有的验证集和测试集来测试的，可以参考这里：https://github.com/LiheYoung/UniMatch/blob/583e32492b0ac150e0946b65864d2dcc642220b8/more-scenarios/medical/dataset/acdc.py#L32
关于测试代码， 我们训练文件中包含了测试的部分。

**Comment by DINGdef** [comment]
好的谢谢！

**Comment by LiheYoung** [comment]
如果需要训练时在valset或testset上验证，只需要将上述的``valtest.txt``改成``val.txt``或``test.txt``即可。

**Comment by DINGdef** [comment]
非常感谢! (●'◡'●)
