### ISSUE TITLE
Image-level Perturbations in LEVIR

### ISSUE THREAD

**Issue by angle011** [LiheYoung/UniMatch#101]
hi @LiheYoung ，Thank you for your great works.I'm interested in your work about remote sense change detection.In your code,you **apply different augments in corresponding dual-temporal images**(You can see [the relevant code](https://github.com/LiheYoung/UniMatch/blob/583e32492b0ac150e0946b65864d2dcc642220b8/more-scenarios/remote-sensing/dataset/semicd.py#L60) about imgA_s1 && imgB_s1).But what troubles me is that Image-level Perturbations may also generate extra changes.

```
    if random.random() < 0.8:
        imgA_s1 = transforms.ColorJitter(0.5, 0.5, 0.5, 0.25)(imgA_s1)
    imgA_s1 = blur(imgA_s1, p=0.5)
    cutmix_box1 = obtain_cutmix_box(imgA_s1.size[0], p=0.5)
    
    if random.random() < 0.8:
        imgB_s1 = transforms.ColorJitter(0.5, 0.5, 0.5, 0.25)(imgB_s1)
    imgB_s1 = blur(imgB_s1, p=0.5)
```

**Comment by LiheYoung** [comment]
A hypothesis is the used color distortions will not alter the change/unchanged labels.
