### ISSUE TITLE
Pascal Voc 数据集的checkpoint

### ISSUE THREAD

**Issue by pjs1** [LiheYoung/UniMatch#102]
请问可以提供Pascal Voc 数据集上的checkpoint嘛

**Comment by LiheYoung** [comment]
抱歉，目前我没有Pascal上的checkpoints了，不过这个数据集很快就可以训练完，你是在复现中遇到了问题吗？

**Comment by pjs1** [comment]
我用两张3090复现您的代码，复现不出来您的精度。

**Comment by ZhiHuiCoding** [comment]
请问两张3090跑了多久跑完实验

**Comment by ZhiHuiCoding** [comment]
Pascal Voc是一定要下git上给的吗

**Comment by LiheYoung** [comment]
@pjs1 可以上传一下log吗？

**Comment by pjs1** [comment]
[Uploading 20230409_175408.log…]()

**Comment by pjs1** [comment]
我复现的是pacal voc（732）基于resnet101，一直差2个点左右

**Comment by pjs1** [comment]
> 请问两张3090跑了多久跑完实验

看哪个数据集，最多是3天左右

**Comment by LiheYoung** [comment]
@pjs1 请再检查一下这个log，链接不对

**Comment by pjs1** [comment]
[20230409_175408.log](https://github.com/LiheYoung/UniMatch/files/13715465/20230409_175408.log)

**Comment by LiheYoung** [comment]
Pascal上我们的总batch size是8 (2 imgs/gpu x 4 gpus), 因此在你2 gpus的情况下，需要将batch size设置为4，而非现在的2

**Comment by pjs1** [comment]
我这边最多只能设置为2 ，不然会报错，我感觉也是这个问题，所以想用您的checkpoint复现精度

**Comment by LiheYoung** [comment]
@pjs1 我上传了Pascal上732 labels和1464 labels下的checkpoints: [ckp_resnet101_732labels](https://drive.google.com/file/d/1495yBhOtwPbc6jeyCPwOunOI2W3TlSZ9/view?usp=sharing), [ckp_resnet101_1464labels](https://drive.google.com/file/d/1Po5qU-hMHTTGy-TYQks8SfkR22cTIv1W/view?usp=sharing)

**Comment by pjs1** [comment]
谢谢！如果有可能的话，可以帮忙提供其他的checkpoints嘛，我想在您的论文上继续研究，麻烦啦！

**Comment by LiheYoung** [comment]
你说的其他checkpoints是指？Cityscapes和COCO上的checkpoints我们已经提供在了README中了，可以通过点击README表格中相应的数值来跳转到对应的checkpoint.

**Comment by pjs1** [comment]
不是，是Pascal数据集里面的366，182，93相关的checkpoints

**Comment by LiheYoung** [comment]
抱歉，我们目前没有足够资源重新再训一遍了

**Comment by pjs1** [comment]
好滴

**Comment by RzzzLiu** [comment]
> 我这边最多只能设置为2 ，不然会报错，我感觉也是这个问题，所以想用您的checkpoint复现精度

两张卡是复现不出来这么好的效果的，最好的话还是4×2，2×4效果都会下降一些
