### ISSUE TITLE
关于特征空间扰动 

### ISSUE THREAD

**Issue by RzzzLiu** [LiheYoung/UniMatch#103]
作者您好，非常感谢你杰出的工作给我很大的启发。请问一下，您是否在训练的时候也有相同的问题，我已经固定了随机数种子，但是感觉加上特征空间扰动有时候不是很稳定，iou浮动能有个上下0.4，这算正常吗

**Comment by LiheYoung** [comment]
我觉得上下浮动0.6以内都是很正常的，可以参考我们跑了三次之间的波动：https://github.com/LiheYoung/UniMatch/tree/main/training-logs/Pascal-VOC-2012/High-Quality-Split-Size321/ResNet-101

**Comment by RzzzLiu** [comment]
> 我觉得上下浮动0.6以内都是很正常的，可以参考我们跑了三次之间的波动：https://github.com/LiheYoung/UniMatch/tree/main/training-logs/Pascal-VOC-2012/High-Quality-Split-Size321/ResNet-101

但是你们这个似乎没有固定随机数种子，固定种子后，浮动还会很大吗。特征空间扰动确实提升性能挺大的，但是就是不是特别稳定

**Comment by LiheYoung** [comment]
是的我们没有固定种子，不过固定种子后只有0.4的波动我也觉得很正常。

**Comment by RzzzLiu** [comment]
> 是的我们没有固定种子，不过固定种子后只有0.4的波动我也觉得很正常。

那请问你们是取平均值，还是取跑的最高的值呢

**Comment by RzzzLiu** [comment]
> 是的我们没有固定种子，不过固定种子后只有0.4的波动我也觉得很正常。

好的，仔细看了你们的log，确实是这样的，非常感谢您！
