### ISSUE TITLE
关于第四页的Algorithm 1

### ISSUE THREAD

**Issue by YUCOCOCS** [LiheYoung/UniMatch#104]
您好，感谢您卓越的贡献，我对您的第四页的算法样式的写法非常欣赏，请问您可以提供一下对应的latex的源代码嘛？感谢

**Comment by LiheYoung** [comment]
你好，可以从arXiv上直接下载latex[源码](https://arxiv.org/e-print/2208.09910)，下载后加个.zip后缀然后解压。

**Comment by YUCOCOCS** [comment]
好滴，谢谢您
