### ISSUE TITLE
Reproducability of PASCAL VOC HQ dataset results

### ISSUE THREAD

**Issue by Srinivasa-Divakar-Bhat** [LiheYoung/UniMatch#106]
I am unable to reproduce the results of the PASCALVOC HQ split. For instance for the split 92 the result in paper is 75.2% while the result I am getting with the code from the repo is 72.52%.
Do you have any insights on what possibly could be the problem?
We have used the data from the link provided in the repo. Could there be any issue with the way data is used? 

Thanks

**Comment by Srinivasa-Divakar-Bhat** [comment]
Using 4 GPUs as stated in the repo fixes the problem.

**Comment by zdk258** [comment]
Why do different GPUS cause such a big difference?

**Comment by LiheYoung** [comment]
Different number of GPUs will affect the total batch size.

**Comment by zdk258** [comment]
如果把batchsize调到总和一样，效果应该差不多吧？
