### ISSUE TITLE
 How much memory its necessary?

### ISSUE THREAD

**Issue by EduardoLawson1** [LiheYoung/UniMatch#109]
you mean 15GB for each GPU or a single one? I have a NVIDIA TITAN X and would like to know if its possible to train on the pascal voc.

_Originally posted by @EduardoLawson1 in https://github.com/LiheYoung/UniMatch/issues/91#issuecomment-1984131116_

**Comment by LiheYoung** [comment]
I mean **totally** 15GB across all GPUS. If you use four GPUS, the per-GPU consumption is around 4GB.
