### ISSUE TITLE
Segmentation model and backbone

### ISSUE THREAD

**Issue by firelight8752** [LiheYoung/UniMatch#11]
Is there any difference between the deeplabv3+ & resnet code here and the code in your previous work（ST++）?
I noticed that there seems to be a difference in parameter settings？

**Comment by LiheYoung** [comment]
The ResNet backbone in ST++ uses a 7x7 conv stem, while in UniMatch, we follow recent works to use a deep stem of three convs. And the output stride in our UniMatch for the Pascal is 16, instead of 8 in ST++.

**Comment by firelight8752** [comment]
Thanks.
Recent work refers to U2PL? Is the segmentation network structure of unimatch and U2PL identical?
In addition, what is the output stride in UniMatch for the Cityscapes?

**Comment by LiheYoung** [comment]
In the arXiv v1 (we may update it in the future), on the Cityscapes, our UniMatch follows U2PL to adopt the output stride of 8. The dimensions in U2PL decoder are also different from most works, you may refer to https://github.com/Haochen-Wang409/U2PL/issues/25. Our decoder is the same as that in CPS and ST++.

**Comment by firelight8752** [comment]
Thank you for your reply. I understand these details. 
It seems that these details are not mentioned in most papers. Can they be regarded as fair comparison?

**Comment by LiheYoung** [comment]
In my experience, the minor modifications in U2PL do not necessarily bring improvement. You may choose them according to your preference.

**Comment by firelight8752** [comment]
Thanks a lot.
