### ISSUE TITLE
轻量级backbone及训练问题

### ISSUE THREAD

**Issue by ZHIZIHUABU** [LiheYoung/UniMatch#110]
使用deeplabv3p作为分割模型太大，我更换为更加轻量级的ppliteseg，并成功运行；请问这种半监督方式能够涨点的原因主要是因为将未标注的数据集送入模型中学习的吗，模型在大量的无标签数据中学习先验知识，所以精度优于完全不输入未标签的数据（全监督）训练方式。
同时，在工业界中的缺陷样本是少样的，大量的正常样本被浪费掉而没有输入模型中进行利用，是否可以使用您这种方式将大量的正常样本作为无标签数据输入模型中进行训练呢，学习正常样本中的先验知识，提高模型的精度。

**Comment by LiheYoung** [comment]
1. 是的，能够涨点是因为引入了无标签数据
2. 我觉得是可行的，但是也需要注意class imbalance的问题，如果有太多的正常样本被显式的学习，可能会导致模型对于异常样本也bias成正常样本
