### ISSUE TITLE
关于sliding_window

### ISSUE THREAD

**Issue by SeonNyo** [LiheYoung/UniMatch#112]
![1](https://github.com/LiheYoung/UniMatch/assets/126854858/3e862b14-3bca-40c9-ba69-7a476e758579)
为什么col和row的移动步长不是grid，而是2/3的grid，这样不是会导致重叠吗，请问作者有什么用意呢

**Comment by LiheYoung** [comment]
这样会导致重叠，这是为了能在重叠部分做一下不同crop下prediction的ensemble
