### ISSUE TITLE
评估和可视化代码

### ISSUE THREAD

**Issue by hmeng7710** [LiheYoung/UniMatch#115]

**Comment by LiheYoung** [comment]
评估代码：https://github.com/LiheYoung/UniMatch/blob/583e32492b0ac150e0946b65864d2dcc642220b8/supervised.py#L33-L85
可视化代码：请参考https://github.com/ZhenZHAO/AugSeg/issues/11

**Comment by hmeng7710** [comment]
感谢您的耐心回复，已找到谢谢。
