### ISSUE TITLE
Minor Typo

### ISSUE THREAD

**Issue by hwanython** [LiheYoung/UniMatch#117]
First, I want to express how inspired I am by your achievements with this project. The work you've done here is truly impressive and has motivated me to apply similar techniques to the field of medical imaging.

While working through the code, I noticed a minor typo in the requirements.txt file. Specifically, "sklearn" should be changed to "scikit-learn" to ensure proper package installation.

I understand this is not a major issue, but I thought it would be helpful to bring it to your attention. Mainly, I wanted to take this opportunity to share how much your work has inspired me and how I am eager to implement it in my projects.

Thank you for your contributions to the community!

Best regards,

**Comment by LiheYoung** [comment]
Thank you for your kind words and your reminder. I have corrected the `requirements.txt` file.
