### ISSUE TITLE
关于自己数据集的问题

### ISSUE THREAD

**Issue by Lengzz3** [LiheYoung/UniMatch#118]
作者您好，我在用于自己数据集时(potsdam一个遥感语义分割数据集)，发现了这样的情况，在1/16 1/2的labeled数据上，跑的结果很正常，但是在1/8 1/4labeled的数据上面跑的结果就比1/16的差，而且差很多，并且发生剧烈震荡，请问一下您有没有相关的经验或者见解呢

**Comment by Lengzz3** [comment]
[1_8.log](https://github.com/user-attachments/files/16798914/1_8.log)
这是1/8labeled的log，我发现在10轮以后开始就开始优化出问题了

**Comment by Lengzz3** [comment]
另外附上其他三种标签类型的结果
[Uploading 1_2.log…]()

**Comment by Lengzz3** [comment]
[1_4.log](https://github.com/user-attachments/files/16817989/1_4.log)
[1_16.log](https://github.com/user-attachments/files/16817992/1_16.log)

**Comment by Lengzz3** [comment]
[1_2.log](https://github.com/user-attachments/files/16818001/1_2.log)
[1_4.log](https://github.com/user-attachments/files/16818002/1_4.log)
[1_16.log](https://github.com/user-attachments/files/16818003/1_16.log)

**Comment by Lengzz3** [comment]
[1_2.log](https://github.com/user-attachments/files/16818006/1_2.log)

**Comment by ZhuangQingYuan** [comment]
> 作者您好，我在用于自己数据集时(potsdam一个遥感语义分割数据集)，发现了这样的情况，在1/16 1/2的labeled数据上，跑的结果很正常，但是在1/8 1/4labeled的数据上面跑的结果就比1/16的差，而且差很多，并且发生剧烈震荡，请问一下您有没有相关的经验或者见解呢
您好这个代码您是咋修改的能用，可以借鉴一下么我现在跑起来所有IOU都是0

**Comment by Lengzz3** [comment]
> > 作者您好，我在用于自己数据集时(potsdam一个遥感语义分割数据集)，发现了这样的情况，在1/16 1/2的labeled数据上，跑的结果很正常，但是在1/8 1/4labeled的数据上面跑的结果就比1/16的差，而且差很多，并且发生剧烈震荡，请问一下您有没有相关的经验或者见解呢
> > 您好这个代码您是咋修改的能用，可以借鉴一下么我现在跑起来所有IOU都是0

我没有进行修改，只是改了config 改了他的数据集路径 并且吧数据集改成了p模式

**Comment by ZhuangQingYuan** [comment]
***@***.***，您可以把联系方式通过这个邮箱发我感谢。希望能和您沟通交流一下。

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月09日 17:40 |
| 收件人 | LiheYoung/UniMatch ***@***.***> |
| 抄送人 | ZhuangQingYuan ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [LiheYoung/UniMatch] 关于自己数据集的问题 (Issue #118) |

作者您好，我在用于自己数据集时(potsdam一个遥感语义分割数据集)，发现了这样的情况，在1/16 1/2的labeled数据上，跑的结果很正常，但是在1/8 1/4labeled的数据上面跑的结果就比1/16的差，而且差很多，并且发生剧烈震荡，请问一下您有没有相关的经验或者见解呢
您好这个代码您是咋修改的能用，可以借鉴一下么我现在跑起来所有IOU都是0

我没有进行修改，只是改了config 改了他的数据集路径 并且吧数据集改成了p模式

**Comment by Lengzz3** [comment]
> ***@***.***，您可以把联系方式通过这个邮箱发我感谢。希望能和您沟通交流一下。
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年12月09日 17:40 | | 收件人 | LiheYoung/UniMatch ***@***.***> | | 抄送人 | ZhuangQingYuan ***@***.***>, Comment ***@***.***> | | 主题 | Re: [LiheYoung/UniMatch] 关于自己数据集的问题 (Issue #118) | 作者您好，我在用于自己数据集时(potsdam一个遥感语义分割数据集)，发现了这样的情况，在1/16 1/2的labeled数据上，跑的结果很正常，但是在1/8 1/4labeled的数据上面跑的结果就比1/16的差，而且差很多，并且发生剧烈震荡，请问一下您有没有相关的经验或者见解呢 您好这个代码您是咋修改的能用，可以借鉴一下么我现在跑起来所有IOU都是0 我没有进行修改，只是改了config 改了他的数据集路径 并且吧数据集改成了p模式 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>
看不到邮箱

**Comment by ZhuangQingYuan** [comment]
1553602380我的qq这个可以看见么

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月09日 18:04 |
| 收件人 | LiheYoung/UniMatch ***@***.***> |
| 抄送人 | ZhuangQingYuan ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [LiheYoung/UniMatch] 关于自己数据集的问题 (Issue #118) |

Closed #118 as completed.
