### ISSUE TITLE
单卡训练时梯度回传报错

### ISSUE THREAD

**Issue by zaiquanyang** [LiheYoung/UniMatch#12]
![image](https://user-images.githubusercontent.com/48671947/199688421-5bfe219b-0dca-4c75-a5de-a187be3aac0a.png)
DDP下使用单卡报错，请问怎么修改呢？多卡没问题。。

**Comment by LiheYoung** [comment]
可以将
https://github.com/LiheYoung/UniMatch/blob/a856ccfccd8d637f522d7ee395a41226eb50c4c3/unimatch.py#L65-L66
修改为
```python
model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[local_rank], broadcast_buffers=False,
                                                  output_device=local_rank, find_unused_parameters=False)
```
