### ISSUE TITLE
About weak and strong image perturbations

### ISSUE THREAD

**Issue by nysp78** [LiheYoung/UniMatch#14]
Hello
In DusPerb framework is said that a shared weak view of an image is used to supervised the 2 strong views. But in the code of Unimatch I see that each strong view has a corresponding weak pseudo label generated from the forward pass of the weak augmented image. So, it seems that there is a weak1 pseudo label to supervise strong1 image and weak2 pseudo label for the strong2 image. The two strong views have generated by attaching a different random patch so they are needed their own pseudo label that is created with a weakly manner. Could you help me with this?

Also, a second question is if the DusPerb framework by itself without feature perturbation is overrunning the baseline FixMatch.

Many thanks

**Comment by LiheYoung** [comment]
1. As you said, the two pseudo labels for the two strong views actually both come from predictions on a weakly augmented image and its CutMixed peer, only with different CutMix regions. So they use a shared weak view.
2. You can refer to Table 6 for comparisons between DusPerb and FixMatch. Our DusPerb improves its FixMatch baseline significantly.

**Comment by LiheYoung** [comment]
Sure. I think you can give an attempt on ClassMix. It may be more effective than CutMix.

**Comment by nysp78** [comment]
The classmix mask is produced from the pseudo label of the weak augmented image. So, if I want to apply classmix to create the two strong views, first I have to forward pass the img_u_w and img_u_w_mix from the network and to obtain 2 pseudo labels from which I will create the classmix masks.Then using those masks I must mix the img_u_s1 with img_u_s1_mix and img_u_s2 with img_u_s2_mix. Could it be effective?

Also I really appreciate your instant replies, many thanks.

**Comment by LiheYoung** [comment]
I think it is worth an attempt.
