### ISSUE TITLE
CPS results on Cityscapes in Table4

### ISSUE THREAD

**Issue by unrealMJ** [LiheYoung/UniMatch#15]
Hi, thanks for your work.

I want to ask why the CPS result on Cityscapes is different from the original paper.

**Comment by LiheYoung** [comment]
Hi, we borrow CPS results from U2PL.

**Comment by unrealMJ** [comment]
您好，感谢回复。
CPS论文中的结果要比U2PL复现的高很多，请问您知道为什么吗？以及如果投论文的话感觉会很容易被审稿人攻击，如果审稿人问这个问题的话应该怎么回复呢？

**Comment by LiheYoung** [comment]
用U2PL中的CPS结果应该是可以的，毕竟U2PL也是这样submit并被接受的。

**Comment by unrealMJ** [comment]
好的，谢谢
