### ISSUE TITLE
Remote Sensing Interpretation

### ISSUE THREAD

**Issue by process852** [LiheYoung/UniMatch#17]
您好，我细读了您出色的半监督语义分割方法，我关注到了附加实验中的变换检测内容，我想请问一下你是如何实施本方法在变换检测任务中，我简单修改源代码使其变为二分类，但是不知道其它具体部分的细节，如果有源代码的话是否可以上传一下相关代码或者描述一下您在应用到变换检测任务中的实现细节。

**Comment by LiheYoung** [comment]
感谢关注。我们主要follow的是[这个工作](https://arxiv.org/abs/2204.08454)，可以参照里面的模型实现，其他模块跟自然图像基本一样。抱歉最近事情有些多，我们大约会在3月20号左右release变化检测部分的代码。

**Comment by process852** [comment]
好的，十分感谢您百忙之中抽出时间回复，期待您的代码发布

**Comment by process852** [comment]
好的，十分感谢您百忙之中抽出时间回复，期待您的代码发布

**Comment by LiheYoung** [comment]
您好，我们已经release了变换检测部分的代码，请见：https://github.com/LiheYoung/UniMatch/tree/main/more-scenarios/remote-sensing. 我们也在最新的arXiv版本中更新了相关的结果。

**Comment by process852** [comment]
好的，非常感谢您的工作，期待您有更好的成果产出。
