### ISSUE TITLE
关于数据集问题

### ISSUE THREAD

**Issue by yang654123** [LiheYoung/UniMatch#2]
你好作者，我想问一下，segmentclass.zip这个文件和官方的数据集不太相同，我想知道这个不同是什么呢。

**Comment by LiheYoung** [comment]
你好，我们的这个SegmentationClass.zip包含了官方提供的1464张高质量mask，以及之后被SBD数据集扩展的9118张略粗糙的标注，共10582张标注。

**Comment by yang654123** [comment]
> 你好，我们的这个SegmentationClass.zip包含了官方提供的1464张高质量mask，以及之后被SBD数据集扩展的9118张略粗糙的标注，共10582张标注。

好的谢谢
