### ISSUE TITLE
Single GPU be used for training? 

### ISSUE THREAD

**Issue by licongguan** [LiheYoung/UniMatch#21]
Hi, Thanks for your great job,
Can a single GPU be used for training? How to evaluate after training, can you provide eval.sh file

**Comment by LiheYoung** [comment]
For Pascal VOC, the GPU memory may be at least 32GB. A single V100 or A100 may be okay. For Cityscapes, you may need a single 80GB A100.

The evaluation process is done after each epoch across the whole training course.

**Comment by licongguan** [comment]
Thank you very much,  How much memory is required to train Cityscapes single GPU?

**Comment by LiheYoung** [comment]
I guess it may require around 80GB for ResNet-50.
