### ISSUE TITLE
Request to Add Paper

### ISSUE THREAD

**Issue by ldkong1205** [LiheYoung/UniMatch#23]
Hi @LiheYoung, thanks for maintaining the list of Awesome Semi-Supervised Semantic Segmentation!

Could you kindly add the following paper into the list? Thanks!
- Title: LaserMix for Semi-Supervised LiDAR Semantic Segmentation
- Venue: CVPR 2023 (Highlight)
- Paper: https://arxiv.org/abs/2207.00026
- Code: https://github.com/ldkong1205/LaserMix

**Comment by LiheYoung** [comment]
Hi lingdong, congrats! 

Already done!
