### ISSUE TITLE
你好，发现一个readme的小问题

### ISSUE THREAD

**Issue by yang654123** [LiheYoung/UniMatch#24]
![image](https://user-images.githubusercontent.com/64208861/229358528-a1e4a4d7-ce7e-4f4b-aefe-a4c7a28d4a77.png)
这里的confidence score是从0.95变成多少呢？

**Comment by yang654123** [comment]
你好，还有一个问题就是，cityscapes的更改resnet输出步长的位置在哪里？

**Comment by LiheYoung** [comment]
1. 这里就是从0.95改成了0
2. cityscapes config文件里的``replace_stride_with_dilation: [False, False, True]``表示output stride为16，之前的[False, True, True]表示output stride为8

**Comment by Ph-Xu** [comment]
您好，感谢您的代码开源。想请教一下UniMatch这个项目中，我想跑more-scenarios下的medical项目，目前已经按照对应readme配置了环境，acdc数据集也下载了，已修改configs下acdc.yaml中数据集的路径，下一步怎么训练模型？ sh train.sh?期待您的答复~

**Comment by LiheYoung** [comment]
可以参考[这里](https://github.com/LiheYoung/UniMatch/tree/main/more-scenarios/medical#unimatch)开启训练，例如：``sh scripts/train.sh 1 20024``

**Comment by Ph-Xu** [comment]
感谢您的回复，我是在本地Ubuntu系统上配置的环境，这个<num_gpu> <port>是怎么给定？

**Comment by LiheYoung** [comment]
<num_gpu>是需要用的GPU数量，设为1就行：

 ``sh scripts/train.sh 1 20024``

**Comment by Ph-Xu** [comment]
谢谢您的回复，上一个问题没有问全，第二个参数<port>看起来是端口号，必须指定嘛，是固定值20024就可以还是随意指定就行，或者不是必须的？另外，是运行more-scenarios/medical/scripts下面的train.sh吗还是主目录下面那个？谢谢您

**Comment by LiheYoung** [comment]
1. 端口号一般在20000-30000之间随便选个数就行
2. 运行more-scenarios/medical/scripts下的train.sh

**Comment by Ph-Xu** [comment]
还是不行，报错了，能指点一下吗
 warnings.warn(
usage: launch.py [-h] [--nnodes NNODES] [--nproc_per_node NPROC_PER_NODE] [--rdzv_backend RDZV_BACKEND] [--rdzv_endpoint RDZV_ENDPOINT] [--rdzv_id RDZV_ID] [--rdzv_conf RDZV_CONF] [--standalone]
                 [--max_restarts MAX_RESTARTS] [--monitor_interval MONITOR_INTERVAL] [--start_method {spawn,fork,forkserver}] [--role ROLE] [-m] [--no_python] [--run_path] [--log_dir LOG_DIR]
                 [-r REDIRECTS] [-t TEE] [--node_rank NODE_RANK] [--master_addr MASTER_ADDR] [--master_port MASTER_PORT] [--use_env]
                 training_script ...
launch.py: error: the following arguments are required: training_script, training_script_args
train.sh: 28: unimatch.py: not found

**Comment by Ph-Xu** [comment]
还是不行，报错了，能指点一下吗
 warnings.warn(
usage: launch.py [-h] [--nnodes NNODES] [--nproc_per_node NPROC_PER_NODE] [--rdzv_backend RDZV_BACKEND] [--rdzv_endpoint RDZV_ENDPOINT] [--rdzv_id RDZV_ID] [--rdzv_conf RDZV_CONF] [--standalone]
                 [--max_restarts MAX_RESTARTS] [--monitor_interval MONITOR_INTERVAL] [--start_method {spawn,fork,forkserver}] [--role ROLE] [-m] [--no_python] [--run_path] [--log_dir LOG_DIR]
                 [-r REDIRECTS] [-t TEE] [--node_rank NODE_RANK] [--master_addr MASTER_ADDR] [--master_port MASTER_PORT] [--use_env]
                 training_script ...
launch.py: error: the following arguments are required: training_script, training_script_args
train.sh: 28: unimatch.py: not found

**Comment by LiheYoung** [comment]
@Ph-Xu Answered in https://github.com/LiheYoung/UniMatch/issues/25

**Comment by MasterBeeee** [comment]
> <num_gpu>是需要用的GPU数量，设为1就行：
> 
> `sh scripts/train.sh 1 20024`

你好 请问如果指定训练的gpu卡号的话该如何指定？ 感谢！

**Comment by MasterBeeee** [comment]
> 

已经解决了，可以在train.sh的训练代码前添加CUDA_VISIBLE_DEVICES=3，4

**Comment by YKtzo** [comment]
你好，我成功复现了您的医学图像训练程序，请问怎样进行推理？

**Comment by LiheYoung** [comment]
我们是在每个训练的epoch结束后都会进行一遍验证的，如果需要推理并保存可视化结果的话，需要自己加一些可视化的代码。

**Comment by YKtzo** [comment]
> 我们是在每个训练的epoch结束后都会进行一遍验证的，如果需要推理并保存可视化结果的话，需要自己加一些可视化的代码。

好的好的，谢谢您的回复

**Comment by yang654123** [comment]
> 1. 这里就是从0.95改成了0
> 2. cityscapes config文件里的`replace_stride_with_dilation: [False, False, True]`表示output stride为16，之前的[False, True, True]表示output stride为8
你好我发现你的原来代码中的cityscape   config 中cropsize是756 但是现在的cropsize改成了801

**Comment by LiheYoung** [comment]
为了跟CPS和U2PL一致。

**Comment by yang654123** [comment]
> 为了跟CPS和U2PL一致。

好的谢谢您
