### ISSUE TITLE
sh train.sh 1 20024报这个错了  能帮忙看看嘛

### ISSUE THREAD

**Issue by Ph-Xu** [LiheYoung/UniMatch#25]
还是不行，报错了，能指点一下吗
 warnings.warn(
usage: launch.py [-h] [--nnodes NNODES] [--nproc_per_node NPROC_PER_NODE] [--rdzv_backend RDZV_BACKEND] [--rdzv_endpoint RDZV_ENDPOINT] [--rdzv_id RDZV_ID] [--rdzv_conf RDZV_CONF] [--standalone]
                 [--max_restarts MAX_RESTARTS] [--monitor_interval MONITOR_INTERVAL] [--start_method {spawn,fork,forkserver}] [--role ROLE] [-m] [--no_python] [--run_path] [--log_dir LOG_DIR]
                 [-r REDIRECTS] [-t TEE] [--node_rank NODE_RANK] [--master_addr MASTER_ADDR] [--master_port MASTER_PORT] [--use_env]
                 training_script ...
launch.py: error: the following arguments are required: training_script, training_script_args
train.sh: 28: unimatch.py: not found

**Comment by LiheYoung** [comment]
是在medical下``sh scripts/train.sh 1 20024``，不是在medical/scripts下``sh train.sh 1 20024``

**Comment by Ph-Xu** [comment]
/root/miniconda3/envs/unimatch/lib/python3.10/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
usage: launch.py [-h] [--nnodes NNODES] [--nproc_per_node NPROC_PER_NODE] [--rdzv_backend RDZV_BACKEND] [--rdzv_endpoint RDZV_ENDPOINT] [--rdzv_id RDZV_ID] [--rdzv_conf RDZV_CONF] [--standalone]
                 [--max_restarts MAX_RESTARTS] [--monitor_interval MONITOR_INTERVAL] [--start_method {spawn,fork,forkserver}] [--role ROLE] [-m] [--no_python] [--run_path] [--log_dir LOG_DIR] [-r REDIRECTS]
                 [-t TEE] [--node_rank NODE_RANK] [--master_addr MASTER_ADDR] [--master_port MASTER_PORT] [--use_env]
                 training_script ...
launch.py: error: the following arguments are required: training_script, training_script_args
scripts/train.sh: 29: unimatch.py: not found

按照您说的来了，还是报这个错。

**Comment by LiheYoung** [comment]
请截一下你的train.sh看一下

**Comment by Ph-Xu** [comment]
![umi](https://user-images.githubusercontent.com/65990771/229983131-b882340d-241d-4b04-85ea-51e784b372aa.png)

**Comment by LiheYoung** [comment]
删掉被注释的``# --master_port=1234``这一行

**Comment by Ph-Xu** [comment]
谢谢您 已经成功解决
