### ISSUE TITLE
关于使用自己的数据集训练

### ISSUE THREAD

**Issue by MasterBeeee** [LiheYoung/UniMatch#26]
您好，首先非常感谢您的贡献！
我的问题是，在尝试使用自己的数据集（医学图像血管分割，所以我直接用了more_scenarios/medical）训练时，我尝试修改more_scenarios/medical/spilts/acdc中的文件，发现有如下很多文件
<img width="602" alt="image" src="https://user-images.githubusercontent.com/77255816/230000308-88ae58d1-5db7-401c-8fda-4b41940d2e0b.png">
我想请问：
1. spilts在这里指的是划分的训练数据集吗，如果训练的话我能否只建一个文件夹放入我的有标签训练数据txt清单和无标签训练数据清单。例如``more_scenarios/medical/spilts/mydataset/1/labeled.text ``以及``more_scenarios/medical/spilts/mydataset/1/unlabeled.text``
2. 对于more_scenarios/medical/spilts/acdc下的其他四个文件，我该分别选择什么数据放进去？
3. 对于训练自己的数据集，除了修改以上所说的,还需要修改别的内容吗

再次感谢您的贡献，同时请您不吝赐教！

**Comment by LiheYoung** [comment]
1. 为了在新的数据集上训练，需要新建你的labeled.txt以及unlabeled.txt，文件中是所有labeled/unlabeled images在``mydataset``下的相对路径
2. 至于acdc下的四个文件，其实不是都必要的，只需要放一个你的val.txt文件在``splits/mydataset``下即可，另外需要修改dataset里https://github.com/LiheYoung/UniMatch/blob/bb3af6c07f1371a8e69e24e31db4f1389427680e/more-scenarios/medical/dataset/acdc.py#L32 ``'splits/%s/valtest.txt'``为``'splits/%s/val.txt'``
3. 最后，当然也需要新建一个config文件，来指定mydataset的路径以及修改dataset的名字(从acdc -> mydataset)。需要注意的是，由于医学图像的数据读取不一定相同，你可能也需要相应的修改dataset中数据读取的部分。

**Comment by MasterBeeee** [comment]
感谢您的回复！
