### ISSUE TITLE
训练完成但是没有自动退出

### ISSUE THREAD

**Issue by 836469383** [LiheYoung/UniMatch#27]
应该不是什么大问题，简单提出来一下
![image](https://user-images.githubusercontent.com/32611043/230286776-9e88a549-3c94-42c7-9e0c-9916a7e3fc30.png)
看到的时候已经过了快俩小时，但是没有退出，不知道大佬知道原因吗。

**Comment by LiheYoung** [comment]
这按理来说已经结束了，“没有退出”是指GPU没有被释放吗？

**Comment by 836469383** [comment]
哦哦，就是会一直保持
![1680764224825](https://user-images.githubusercontent.com/32611043/230295685-25b85f7e-ae6b-4290-90e5-b202710b012f.jpg)
这样，需要ctrl+c才会出现命令行（即  ‘’user@user：/path/to/project$‘’），GPU是释放了的

**Comment by LiheYoung** [comment]
这个输出的log文件，不需要ctrl+c的，程序已经结束了

**Comment by 836469383** [comment]
啊好吧，感谢大佬的回复~不自动退出也没影响，就是有点奇怪，回头再看看吧 😘
