### ISSUE TITLE
请问device-side assert triggered怎么解决

### ISSUE THREAD

**Issue by MasterBeeee** [LiheYoung/UniMatch#29]
你好 抱歉打扰，在训练的时候发生了如下报错
<img width="1289" alt="image" src="https://user-images.githubusercontent.com/77255816/231325568-e2a658e7-7ed0-49f0-bda5-0a7e495c6f6d.png">
网上搜索大多都说是分类任务报的错，没有什么帮助，请问您有遇到过吗 ，该如何解决呢

**Comment by LiheYoung** [comment]
一般来说是因为人工标注的mask中存在比网络输出的类别数 (configs中的``nclass``)更大的类别（准确来说是大于或等于）。比如如果你的``nclass``设置的是21，但是mask中存在25这样的类别index，那就会报这样的错，需要检查一下mask。

**Comment by MasterBeeee** [comment]
感谢您的回复，我的mask做灰度图读入后应该只有背景和血管两个类，好奇怪

**Comment by LiheYoung** [comment]
可以``print(torch.unique(mask))``确认一下是否只有0和1。

**Comment by MasterBeeee** [comment]
非常感谢您的回复
改了半天发现是我mask在transform.resize后改了像素值，原来取值只有0，255（黑色和白色）的像素变了，改完后现在输出的``print(`torch.unique(torch.from_numpy(mask).long()))``结果是``tensor([  0, 255])``(不是0，1会影响吗) ，然后我修改了``nclass``为2然后还是报错
<img width="1290" alt="image" src="https://user-images.githubusercontent.com/77255816/231402095-f1ac9af9-cc18-4d9e-ac1c-f365d61cfb97.png">

**Comment by LiheYoung** [comment]
需要将255的像素改成1才行

**Comment by MasterBeeee** [comment]
您好 感谢您的回复，将255的像素改为1之后确实成功开始了训练。 我在用得到的模型进行test时候，发现得到的output是两通道的（torch.size[1,2,480,480]）,请问这样是否正常？

**Comment by LiheYoung** [comment]
对的

**Comment by MasterBeeee** [comment]
您好，我在对预测的图像尝试转换为正常模型时，
![image](https://user-images.githubusercontent.com/77255816/234618536-26b2b9e8-6d95-4136-a698-1dd7f13a6a8e.png)
发现argmax后的tensor全部为1，
![image](https://user-images.githubusercontent.com/77255816/234618782-d1d29149-e19b-4356-a50e-b744a6b1f7e0.png)
发现是因为两个通道总是有一个通道的像素比另外一个的大，后来放弃使用argmax而是直接将两个通道的值相加后*255，发现出来的结果基本能还原轮廓但是很奇怪，请问您有试过将预测的结果转换成图像吗？有遇到类似问题吗

**Comment by bit-ygd** [comment]
> 您好 感谢您的回复，将255的像素改为1之后确实成功开始了训练。 我在用得到的模型进行test时候，发现得到的output是两通道的（torch.size[1,2,480,480]）,请问这样是否正常？
你好，我在进行医学图像分割时也遇到了相同的问题，请问你是如何修改代码的
