### ISSUE TITLE
Config file for high resolution training for Pascal VOC

### ISSUE THREAD

**Issue by gavinwxy** [LiheYoung/UniMatch#3]
Hi,

Thanks for sharing your code. I found that only config file for pascal 321x321 is presented. Could you please provide your training settings for high resolution training which is 513x513? Or they just share the same setting. Thanks.

**Comment by LiheYoung** [comment]
You only need to modify the ``321`` to ``513`` in the config file, and then will obtain a better performance. Thanks.

**Comment by gavinwxy** [comment]
Thanks for the reply.
