### ISSUE TITLE
您好，请问下如何对训练好的模型进行单卡预测？

### ISSUE THREAD

**Issue by xiaoqiang-lu** [LiheYoung/UniMatch#30]
您好，作者。我想利用训练好的模型制作预测结果，按照训练函数中的分布式模型构建方式，可以成功进行多卡预测。但在进行非分布式构建模型及预测时，我遇到了下述问题：

![image](https://user-images.githubusercontent.com/74170176/231371077-ce78ee78-70cd-4e73-8ae7-70e8d4e03c6a.png)

构建模型的代码如下：

![image](https://user-images.githubusercontent.com/74170176/231371337-d7902164-e151-4a8f-8bfc-757fc7abab19.png)

**Comment by LiheYoung** [comment]
你好，需要仿照``unimatch.py``里对model用DDP wrap一下再load_state_dict:
```
model = DeepLabV3Plus(cfg)
model.cuda()
model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[local_rank], broadcast_buffers=False,
                                                  output_device=local_rank, find_unused_parameters=False)
model.load_state_dict(checkpoint['model'])
```

**Comment by xiaoqiang-lu** [comment]
您好，出现了一个新的问题：

![image](https://user-images.githubusercontent.com/74170176/231377264-bd4976f9-a91b-4de5-bbb7-670f747dc765.png)

似乎是单卡加载分布式训练模型时，所存的模型需要为：model.module.state_dict()
我注意到最初版本的代码里存模型时用的是model.module.state_dict()，当前版本用的是model.state_dict()

**Comment by LiheYoung** [comment]
如果是以model.state_dict()直接保存的（state_dict的keys里包含"module"），那需要DDP wrap一下再load；如果是以model.module.state_dict()保存的（state_dict的keys里不包含"module"），那可以直接load。上面这个报错是你没有配置DDP，可以仿照``unimatch.py``里设置一下: 
https://github.com/LiheYoung/UniMatch/blob/bb3af6c07f1371a8e69e24e31db4f1389427680e/unimatch.py#L40

**Comment by xiaoqiang-lu** [comment]
您好，添加上述之后：

![image](https://user-images.githubusercontent.com/74170176/231382938-7c205c5a-e97d-41aa-820e-e54c399eeac1.png)

出现错误：

![image](https://user-images.githubusercontent.com/74170176/231383096-77cf2346-8c16-4dc9-8ca2-91e25ef079fc.png)

**Comment by LiheYoung** [comment]
需要加上这个：
https://github.com/LiheYoung/UniMatch/blob/bb3af6c07f1371a8e69e24e31db4f1389427680e/unimatch.py#L28
另外注意启动方式也使用train.sh里的

**Comment by xiaoqiang-lu** [comment]
感谢您的解答，这似乎绕回到分布式构建模型，但是指定了单卡。我将torch.nn.parallel.DistributedDataParallel替换为torch.nn.DataParallel解决了此问题，能够直接启动。

谢谢您的耐心指点，祝科研顺利~

**Comment by LiheYoung** [comment]
好的～
