### ISSUE TITLE
Compared to the previous version

### ISSUE THREAD

**Issue by Jack-bo1220** [LiheYoung/UniMatch#31]
I noticed that compared to the previous version, the latest code has removed 'multi_grid' from the backbone (resnet) and changed the settings of parameters such as dilations. 

May I ask if the adjusted version can improve the performance?

**Comment by LiheYoung** [comment]
To avoid confusion, we only make these changes on **Cityscapes**. 

We change the``replace_stride_with_dilation`` from ``[False, True, True]`` to ``[False, False, True]``. Actually, this will lower the performance (around 1%), but will significantly speed up the training (around 2x) and require much less GPU memory. As for the ``multi_grid``, we do not think it makes much difference to performance. 

Our improvements on Cityscapes from arXiv v1 to arXiv v2 (camera-ready version) mainly come from the confidence threshold changed from ``0.95`` to ``0``.

**Comment by Jack-bo1220** [comment]
Thanks.

**Comment by Jack-bo1220** [comment]
And will the latest weights on Cityscapes be made public?

**Comment by LiheYoung** [comment]
Which weight do you need?

**Comment by Jack-bo1220** [comment]
If possible, could you provide latest trained models on the Cityscapes dataset? 
I think it will help other researchers quickly reproduce latest results, thanks a lot!

**Comment by LiheYoung** [comment]
We have provided the checkpoints of our best models for each split and each backbone on [Cityscapes](https://github.com/LiheYoung/UniMatch#cityscapes) and [COCO](https://github.com/LiheYoung/UniMatch#coco). You can click on the numbers to download corresponding checkpoints.

**Comment by Jack-bo1220** [comment]
Thanks a lot!

**Comment by Jack-bo1220** [comment]
> [我们为Cityscapes](https://github.com/LiheYoung/UniMatch#cityscapes)和[COCO](https://github.com/LiheYoung/UniMatch#coco)上的每个拆分和每个主干提供了我们最好的模型的检查点。您可以点击数字下载相应的检查点。

There is an error using the weight of Cityscapes here

RuntimeError: Error(s) in loading state_dict for DeepLabV3Plus:
        Missing key(s) in state_dict: "backbone.conv1.0.weight", "backbone.conv1.1.weight", "backbone.conv1.1.bias", "backbone.conv1.1.running_mean", "backbone.conv1.1.running_var", "backbone.conv1.3.weight", "backbone.conv1.4.weight", "backbone.conv1.4.bias", "backbone.conv1.4.running_mean", "backbone.conv1.4.running_var", "backbone.conv1.6.weight", "backbone.bn1.weight", "backbone.bn1.bias", "backbone.bn1.running_mean", "backbone.bn1.running_var", "backbone.layer1.0.conv1.weight", "backbone.layer1.0.bn1.weight", "backbone.layer1.0.bn1.bias", "backbone.layer1.0.bn1.running_mean", "backbone.layer1.0.bn1.running_var", "backbone.layer1.0.conv2.weight", "backbone.layer1.0.bn2.weight", "backbone.layer1.0.bn2.bias", "backbone.layer1.0.bn2.running_mean", "backbone.layer1.0.bn2.running_var", "backbone.layer1.0.conv3.weight", "backbone.layer1.0.bn3.weight", "backbone.layer1.0.bn3.bias", "backbone.layer1.0.bn3.running_mean", "backbone.layer1.0.bn3.running_var", "backbone.layer1.0.downsample.0.weight", "backbone.layer1.0.downsample.1.weight", "backbone.layer1.0.downsample.1.bias", "backbone.layer1.0.downsample.1.running_mean", "backbone.layer1.0.downsample.1.running_var", "backbone.layer1.1.conv1.weight", "backbone.layer1.1.bn1.weight", "backbone.layer1.1.bn1.bias", "backbone.layer1.1.bn1.running_mean", "backbone.layer1.1.bn1.running_var", "backbone.layer1.1.conv2.weight", "backbone.layer1.1.bn2.weight", "backbone.layer1.1.bn2.bias", "backbone.layer1.1.bn2.running_mean", "backbone.layer1.1.bn2.running_var", "backbone.layer1.1.conv3.weight", "backbone.layer1.1.bn3.weight", "backbone.layer1.1.bn3.bias", "backbone.layer1.1.bn3.running_mean", "backbone.layer1.1.bn3.running_var", "backbone.layer1.2.conv1.weight", "backbone.layer1.2.bn1.weight", "backbone.layer1.2.bn1.bias", "backbone.layer1.2.bn1.running_mean", "backbone.layer1.2.bn1.running_var", "backbone.layer1.2.conv2.weight", "backbone.layer1.2.bn2.weight", "backbone.layer1.2.bn2.bias", "backbone.layer1.2.bn2.running_mean", "backbone.layer1.2.bn2.running_var", "backbone.layer1.2.conv3.weight", "backbone.layer1.2.bn3.weight", "backbone.layer1.2.bn3.bias", "backbone.layer1.2.bn3.running_mean", "backbone.layer1.2.bn3.running_var", "backbone.layer2.0.conv1.weight", "backbone.layer2.0.bn1.weight", "backbone.layer2.0.bn1.bias", "backbone.layer2.0.bn1.running_mean", "backbone.layer2.0.bn1.running_var", "backbone.layer2.0.conv2.weight", "backbone.layer2.0.bn2.weight", "backbone.layer2.0.bn2.bias", "backbone.layer2.0.bn2.running_mean", "backbone.layer2.0.bn2.running_var", "backbone.layer2.0.conv3.weight", "backbone.layer2.0.bn3.weight", "backbone.layer2.0.bn3.bias", "backbone.layer2.0.bn3.running_mean", "backbone.layer2.0.bn3.running_var", "backbone.layer2.0.downsample.0.weight", "backbone.layer2.0.downsample.1.weight", "backbone.layer2.0.downsample.1.bias", "backbone.layer2.0.downsample.1.running_mean", "backbone.layer2.0.downsample.1.running_var", "backbone.layer2.1.conv1.weight", "backbone.layer2.1.bn1.weight", "backbone.layer2.1.bn1.bias", "backbone.layer2.1.bn1.running_mean", "backbone.layer2.1.bn1.running_var", "backbone.layer2.1.conv2.weight", "backbone.layer2.1.bn2.weight", "backbone.layer2.1.bn2.bias", "backbone.layer2.1.bn2.running_mean", "backbone.layer2.1.bn2.running_var", "backbone.layer2.1.conv3.weight", "backbone.layer2.1.bn3.weight", "backbone.layer2.1.bn3.bias", "backbone.layer2.1.bn3.running_mean", "backbone.layer2.1.bn3.running_var", "backbone.layer2.2.conv1.weight", "backbone.layer2.2.bn1.weight", "backbone.layer2.2.bn1.bias", "backbone.layer2.2.bn1.running_mean", "backbone.layer2.2.bn1.running_var", "backbone.layer2.2.conv2.weight", "backbone.layer2.2.bn2.weight", "backbone.layer2.2.bn2.bias", "backbone.layer2.2.bn2.running_mean", "backbone.layer2.2.bn2.running_var", "backbone.layer2.2.conv3.weight", "backbone.layer2.2.bn3.weight", "backbone.layer2.2.bn3.bias", "backbone.layer2.2.bn3.running_mean", "backbone.layer2.2.bn3.running_var", "backbone.layer2.3.conv1.weight", "backbone.layer2.3.bn1.weight", "backbone.layer2.3.bn1.bias", "backbone.layer2.3.bn1.running_mean", "backbone.layer2.3.bn1.running_var", "backbone.layer2.3.conv2.weight", "backbone.layer2.3.bn2.weight", "backbone.layer2.3.bn2.bias", "backbone.layer2.3.bn2.running_mean", "backbone.layer2.3.bn2.running_var", "backbone.layer2.3.conv3.weight", "backbone.layer2.3.bn3.weight", "backbone.layer2.3.bn3.bias", "backbone.layer2.3.bn3.running_mean", "backbone.layer2.3.bn3.running_var", "backbone.layer3.0.conv1.weight", "backbone.layer3.0.bn1.weight", "backbone.layer3.0.bn1.bias", "backbone.layer3.0.bn1.running_mean", "backbone.layer3.0.bn1.running_var", "backbone.layer3.0.conv2.weight", "backbone.layer3.0.bn2.weight", "backbone.layer3.0.bn2.bias", "backbone.layer3.0.bn2.running_mean", "backbone.layer3.0.bn2.running_var", "backbone.layer3.0.conv3.weight", "backbone.layer3.0.bn3.weight", "backbone.layer3.0.bn3.bias", "backbone.layer3.0.bn3.running_mean", "backbone.layer3.0.bn3.running_var", "backbone.layer3.0.downsample.0.weight", "backbone.layer3.0.downsample.1.weight", "backbone.layer3.0.downsample.1.bias", "backbone.layer3.0.downsample.1.running_mean", "backbone.layer3.0.downsample.1.running_var", "backbone.layer3.1.conv1.weight", "backbone.layer3.1.bn1.weight", "backbone.layer3.1.bn1.bias", "backbone.layer3.1.bn1.running_mean", "backbone.layer3.1.bn1.running_var", "backbone.layer3.1.conv2.weight", "backbone.layer3.1.bn2.weight", "backbone.layer3.1.bn2.bias", "backbone.layer3.1.bn2.running_mean", "backbone.layer3.1.bn2.running_var", "backbone.layer3.1.conv3.weight", "backbone.layer3.1.bn3.weight", "backbone.layer3.1.bn3.bias", "backbone.layer3.1.bn3.running_mean", "backbone.layer3.1.bn3.running_var", "backbone.layer3.2.conv1.weight", "backbone.layer3.2.bn1.weight", "backbone.layer3.2.bn1.bias", "backbone.layer3.2.bn1.running_mean", "backbone.layer3.2.bn1.running_var", "backbone.layer3.2.conv2.weight", "backbone.layer3.2.bn2.weight", "backbone.layer3.2.bn2.bias", "backbone.layer3.2.bn2.running_mean", "backbone.layer3.2.bn2.running_var", "backbone.layer3.2.conv3.weight", "backbone.layer3.2.bn3.weight", "backbone.layer3.2.bn3.bias", "backbone.layer3.2.bn3.running_mean", "backbone.layer3.2.bn3.running_var", "backbone.layer3.3.conv1.weight", "backbone.layer3.3.bn1.weight", "backbone.layer3.3.bn1.bias", "backbone.layer3.3.bn1.running_mean", "backbone.layer3.3.bn1.running_var", "backbone.layer3.3.conv2.weight", "backbone.layer3.3.bn2.weight", "backbone.layer3.3.bn2.bias", "backbone.layer3.3.bn2.running_mean", "backbone.layer3.3.bn2.running_var", "backbone.layer3.3.conv3.weight", "backbone.layer3.3.bn3.weight", "backbone.layer3.3.bn3.bias", "backbone.layer3.3.bn3.running_mean", "backbone.layer3.3.bn3.running_var", "backbone.layer3.4.conv1.weight", "backbone.layer3.4.bn1.weight", "backbone.layer3.4.bn1.bias", "backbone.layer3.4.bn1.running_mean", "backbone.layer3.4.bn1.running_var", "backbone.layer3.4.conv2.weight", "backbone.layer3.4.bn2.weight", "backbone.layer3.4.bn2.bias", "backbone.layer3.4.bn2.running_mean", "backbone.layer3.4.bn2.running_var", "backbone.layer3.4.conv3.weight", "backbone.layer3.4.bn3.weight", "backbone.layer3.4.bn3.bias", "backbone.layer3.4.bn3.running_mean", "backbone.layer3.4.bn3.running_var", "backbone.layer3.5.conv1.weight", "backbone.layer3.5.bn1.weight", "backbone.layer3.5.bn1.bias", "backbone.layer3.5.bn1.running_mean", "backbone.layer3.5.bn1.running_var", "backbone.layer3.5.conv2.weight", "backbone.layer3.5.bn2.weight", "backbone.layer3.5.bn2.bias", "backbone.layer3.5.bn2.running_mean", "backbone.layer3.5.bn2.running_var", "backbone.layer3.5.conv3.weight", "backbone.layer3.5.bn3.weight", "backbone.layer3.5.bn3.bias", "backbone.layer3.5.bn3.running_mean", "backbone.layer3.5.bn3.running_var", "backbone.layer4.0.conv1.weight", "backbone.layer4.0.bn1.weight", "backbone.layer4.0.bn1.bias", "backbone.layer4.0.bn1.running_mean", "backbone.layer4.0.bn1.running_var", "backbone.layer4.0.conv2.weight", "backbone.layer4.0.bn2.weight", "backbone.layer4.0.bn2.bias", "backbone.layer4.0.bn2.running_mean", "backbone.layer4.0.bn2.running_var", "backbone.layer4.0.conv3.weight", "backbone.layer4.0.bn3.weight", "backbone.layer4.0.bn3.bias", "backbone.layer4.0.bn3.running_mean", "backbone.layer4.0.bn3.running_var", "backbone.layer4.0.downsample.0.weight", "backbone.layer4.0.downsample.1.weight", "backbone.layer4.0.downsample.1.bias", "backbone.layer4.0.downsample.1.running_mean", "backbone.layer4.0.downsample.1.running_var", "backbone.layer4.1.conv1.weight", "backbone.layer4.1.bn1.weight", "backbone.layer4.1.bn1.bias", "backbone.layer4.1.bn1.running_mean", "backbone.layer4.1.bn1.running_var", "backbone.layer4.1.conv2.weight", "backbone.layer4.1.bn2.weight", "backbone.layer4.1.bn2.bias", "backbone.layer4.1.bn2.running_mean", "backbone.layer4.1.bn2.running_var", "backbone.layer4.1.conv3.weight", "backbone.layer4.1.bn3.weight", "backbone.layer4.1.bn3.bias", "backbone.layer4.1.bn3.running_mean", "backbone.layer4.1.bn3.running_var", "backbone.layer4.2.conv1.weight", "backbone.layer4.2.bn1.weight", "backbone.layer4.2.bn1.bias", "backbone.layer4.2.bn1.running_mean", "backbone.layer4.2.bn1.running_var", "backbone.layer4.2.conv2.weight", "backbone.layer4.2.bn2.weight", "backbone.layer4.2.bn2.bias", "backbone.layer4.2.bn2.running_mean", "backbone.layer4.2.bn2.running_var", "backbone.layer4.2.conv3.weight", "backbone.layer4.2.bn3.weight", "backbone.layer4.2.bn3.bias", "backbone.layer4.2.bn3.running_mean", "backbone.layer4.2.bn3.running_var", "head.b0.0.weight", "head.b0.1.weight", "head.b0.1.bias", "head.b0.1.running_mean", "head.b0.1.running_var", "head.b1.0.weight", "head.b1.1.weight", "head.b1.1.bias", "head.b1.1.running_mean", "head.b1.1.running_var", "head.b2.0.weight", "head.b2.1.weight", "head.b2.1.bias", "head.b2.1.running_mean", "head.b2.1.running_var", "head.b3.0.weight", "head.b3.1.weight", "head.b3.1.bias", "head.b3.1.running_mean", "head.b3.1.running_var", "head.b4.gap.1.weight", "head.b4.gap.2.weight", "head.b4.gap.2.bias", "head.b4.gap.2.running_mean", "head.b4.gap.2.running_var", "head.project.0.weight", "head.project.1.weight", "head.project.1.bias", "head.project.1.running_mean", "head.project.1.running_var", "reduce.0.weight", "reduce.1.weight", "reduce.1.bias", "reduce.1.running_mean", "reduce.1.running_var", "fuse.0.weight", "fuse.1.weight", "fuse.1.bias", "fuse.1.running_mean", "fuse.1.running_var", "fuse.3.weight", "fuse.4.weight", "fuse.4.bias", "fuse.4.running_mean", "fuse.4.running_var", "classifier.weight", "classifier.bias". 
        Unexpected key(s) in state_dict: "model", "optimizer", "epoch", "previous_best".

**Comment by LiheYoung** [comment]
As you can see in the error information, "Unexpected key(s) in state_dict: "model", "optimizer", "epoch", "previous_best"".

You should load ``checkpoint['model']``, as done in: https://github.com/LiheYoung/UniMatch/blob/a5d2a52223d000d14959b2100d4e0324a4f871e9/unimatch.py#L99

**Comment by tanveer6715** [comment]
> As you can see in the error information, "Unexpected key(s) in state_dict: "model", "optimizer", "epoch", "previous_best"".
> 
> You should load `checkpoint['model']`, as done in:
> 
> https://github.com/LiheYoung/UniMatch/blob/a5d2a52223d000d14959b2100d4e0324a4f871e9/unimatch.py#L99

I have done it as you said but then it show this error. How to avoid this key errors?:
![image](https://user-images.githubusercontent.com/84553134/234539011-8995df0c-313b-4bc1-b3d9-d8fc92f813d4.png)

**Comment by Jack-bo1220** [comment]
> > As you can see in the error information, "Unexpected key(s) in state_dict: "model", "optimizer", "epoch", "previous_best"".
> > You should load `checkpoint['model']`, as done in:
> > https://github.com/LiheYoung/UniMatch/blob/a5d2a52223d000d14959b2100d4e0324a4f871e9/unimatch.py#L99
> 
> I have done it as you said but then it show this error. How to avoid this key errors?: ![image](https://user-images.githubusercontent.com/84553134/234539011-8995df0c-313b-4bc1-b3d9-d8fc92f813d4.png)

Hi, you should   
model = torch.nn.parallel.DistributedDataParallel(model)
