### ISSUE TITLE
Unlabeled Images Mask in Split

### ISSUE THREAD

**Issue by rahulsnkr** [LiheYoung/UniMatch#33]
Hi, thank you for the work!

Not sure if I'm missing something but why are we including the masks for the unlabeled images in the `split` folder? I see that in [semi.py](https://github.com/LiheYoung/UniMatch/blob/main/dataset/semi.py) we are processing the masks for the unlabeled images as well, but according to Algorithm 1 in the paper, we get the predicted mask from the perturbed images.

Is it possible to run this model on a dataset for which we don't have the masks for the unlabeled images?

**Comment by LiheYoung** [comment]
We do not use manual annotations of unlabeled images for training. The masks of unlabeled images are used to record padded regions during image pre-processing.

If you do not have masks, you can simply duplicate the image paths in each line of split file, for example:
``path/of/image1.jpg path/of/image1.jpg``

Then you need to modify this line:
https://github.com/LiheYoung/UniMatch/blob/a5d2a52223d000d14959b2100d4e0324a4f871e9/dataset/semi.py#L35 to:
```python
mask = Image.fromarray(np.zeros((img.size[1], img.size[0]), dtype=np.uint8))
```

**Comment by rahulsnkr** [comment]
thanks for the clarification!

**Comment by tanveer6715** [comment]
> We do not use manual annotations of unlabeled images for training. The masks of unlabeled images are used to record padded regions during image pre-processing.
> 
> If you do not have masks, you can simply duplicate the image paths in each line of split file, for example: `path/of/image1.jpg path/of/image1.jpg`
> 
> Then you need to modify this line:
> 
> https://github.com/LiheYoung/UniMatch/blob/a5d2a52223d000d14959b2100d4e0324a4f871e9/dataset/semi.py#L35
> 
> to:
> ```python
> mask = Image.fromarray(np.zeros((img.size[1], img.size[0]), dtype=np.uint8))
> ```

Hi,
This process the data in the training when we do not want to use labels in the unlabeled data split but in the validation step after each epoch the model  shows 0 miou as it do not use masks in the validation step as well to compare the predictions. How to tackle this problem?

**Comment by LiheYoung** [comment]
@tanveer6715  Add  a condition: 
```python
if self.mode == 'train_u':
    mask = Image.fromarray(np.zeros((img.size[1], img.size[0]), dtype=np.uint8))
else:
    mask = Image.fromarray(np.array(Image.open(os.path.join(self.root, id.split(' ')[1])))) 
```
