### ISSUE TITLE
Question for CutMix

### ISSUE THREAD

**Issue by kevinshieh0225** [LiheYoung/UniMatch#34]
Hi, thanks for the great work!

I have found that you used additional dataloader for the cutmix sources.

Since most of the work will mix by using the image from the same loaded batches, I was wondering what is the intention of using mixing sources from another batch, and will it affect the training result by using the common setting which only using one dataloader and the same batch for mixing? Thanks!

**Comment by LiheYoung** [comment]
Actually, it is not an intentional practice. We later found that we can simply CutMix an image batch with its shuffled version. The performance will not be affected.

**Comment by kevinshieh0225** [comment]
That is great! It will be easier to implement if so!
