### ISSUE TITLE
Try to apply teacher model?

### ISSUE THREAD

**Issue by Wenlve-Zhou** [LiheYoung/UniMatch#35]
Thank you so much for your wonderful work! Have you considered introducing the Teacher model (EMA) to produce the output of the weakly view? Since in the semi-supervised semantic segmentation, the Teacher model can produce a more robust output.

**Comment by LiheYoung** [comment]
Hi, thank you for your interest. Sorry that we haven't employed a teacher model.

**Comment by Wenlve-Zhou** [comment]
Yes, I know. Thanks for the reply. And do you think better gains will be achieved by introducing the teacher model?

**Comment by LiheYoung** [comment]
I guess if properly applied, the EMA teacher will bring some extra improvement in high-label regimes, such as 1/4, 1/2 splits.
