### ISSUE TITLE
Weight File for PASCALVOC

### ISSUE THREAD

**Issue by suesuekkim** [LiheYoung/UniMatch#36]
I can find the Cityscapes and COCO weights, but couldn't find any PASCALVOC weight file. As I reproduce the same code without modifications of yours, also checked the config file (as below), there was a slight gap of 2-3%. I got 76.91 on 732 split, which yours were 79.9. Can you upload any weight file for PASCALVOC? Thank you. Really appreciate your works by the way!

[2023-04-10 19:41:31,486][    INFO] {'backbone': 'resnet101',
 'batch_size': 2,
 'conf_thresh': 0.95,
 'config': 'configs/pascal.yaml',
 'criterion': {'kwargs': {'ignore_index': 255}, 'name': 'CELoss'},
 'crop_size': 321,
 'data_root': '/data2/ksy/PASCALVOC2012/',
 'dataset': 'pascal',
 'dilations': [6, 12, 18],
 'epochs': 80,
 'labeled_id_path': 'splits/pascal/732/labeled.txt',
 'local_rank': 0,
 'lr': 0.001,
 'lr_multi': 10.0,
 'model': 'deeplabv3plus',
 'nclass': 21,
 'ngpus': 2,
 'port': 20024,
 'replace_stride_with_dilation': [False, False, True],
 'save_path': 'exp/pascal/unimatch/r101/732',
 'unlabeled_id_path': 'splits/pascal/732/unlabeled.txt'}

**Comment by LiheYoung** [comment]
You should maintain a total batch size of 8. However, your current total batch size is only 4 (2 imgs / GPU x 2 GPUs).
