### ISSUE TITLE
Where does the pre-training weight of resnet50 come from？

### ISSUE THREAD

**Issue by yiiizuo** [LiheYoung/UniMatch#38]
Where does the pre-training weight of resnet50 come from？
I would like to know where the pre training weights provided in readme are obtained from? I found that there is a significant difference between the results of the resnet50 weight training provided on the Pytorch official website and the weight training results loaded in Readme.

pytorch resnet50: https://download.pytorch.org/models/resnet50-19c8e357.pth

**Comment by LiheYoung** [comment]
Semantic segmentation works mostly adopt a slightly modified ResNet for better performance. Our ResNet structure and pre-trained weights are the same as other works. I remember it may come from EncNet.
