### ISSUE TITLE
How much memory do you use during training?

### ISSUE THREAD

**Issue by zhk779** [LiheYoung/UniMatch#39]
Hello, I appreciate your generosity in sharing your code. I have attempted to replicate your work on two GTX 4090s with a combined memory of 24 GB.  However, during the training process on the cityscapes dataset, the GPU memory allocation proved insufficient, forcing me to reduce the batch size to 1 and the backbone to ResNet50. Despite these adjustments, the program still consumes a considerable amount of memory at around 23 GB. I was wondering how much memory is typically required for the model during your own training process?"

**Comment by LiheYoung** [comment]
I can not remember very clearly. I think it may be around 80G-120G, because the training resolution of Cityscapes is very large. I think you can try a lower resolution, e.g., 513x513. But the performance will be substantially downgraded.

**Comment by zhk779** [comment]
Ok, Thanks for your replly!

**Comment by yang654123** [comment]
> I can not remember very clearly. I think it may be around 80G-120G, because the training resolution of Cityscapes is very large. I think you can try a lower resolution, e.g., 513x513. But the performance will be substantially downgraded.

> I can not remember very clearly. I think it may be around 80G-120G, because the training resolution of Cityscapes is very large. I think you can try a lower resolution, e.g., 513x513. But the performance will be substantially downgraded.

hello,author! i used 16G×8(total 128G) V100  can't reproduce the code,and i have to change the batchsize to 1 ,but the MIOU lower than your paper written.so how can i do to solve this problem.

**Comment by LiheYoung** [comment]
@yang654123  Please show me your training log.

**Comment by yang654123** [comment]
[](url)
[20230616_205458.txt](https://github.com/LiheYoung/UniMatch/files/11770596/20230616_205458.txt)

**Comment by LiheYoung** [comment]
The "out of memory" error is raised at ``model.cuda()``. The training has not yet started here. So I think it may be your GPU problem. Perhaps the memory has not been freed?

**Comment by yang654123** [comment]
> The "out of memory" error is raised at `model.cuda()`. The training has not yet started here. So I think it may be your GPU problem. Perhaps the memory has not been freed?

[](url)
[20230616_205458.txt](https://github.com/LiheYoung/UniMatch/files/11771222/20230616_205458.txt)

**Comment by yang654123** [comment]
> The "out of memory" error is raised at `model.cuda()`. The training has not yet started here. So I think it may be your GPU problem. Perhaps the memory has not been freed?

[](url)
[20230616_222232.txt](https://github.com/LiheYoung/UniMatch/files/11771248/20230616_222232.txt)

**Comment by LiheYoung** [comment]
I have just tried bs=2 (per GPU), it can successfully run on 8 x 32GB V100 (requires 25.7GB memory per GPU). Your provided log shows you use bs=2 but your GPU max memory is only 16GB. Therefore it is not enough. 

You should use bs=1 (per GPU) **with 8 GPUs**, then the total batch size is 8, which is the same as our total batch size on Cityscapes.

Besides, it seems you do not use our latest code. It is recommended to use the latest commit.
