### ISSUE TITLE
About Pascal Voc 2012 results

### ISSUE THREAD

**Issue by tanveer6715** [LiheYoung/UniMatch#42]
Hi,
Great work. I have some confusion about Supervised baseline and UniMatch comparison in Pascal Voc 2012 dataset.
1. What is Supervised baseline in your study?
2. In the Pascal Voc dataset if we used all labelled dataset then how it can be used as semi supervised training. I have attached the table you presented. Please explain the last column of this table .
Thanks
![image](https://github.com/LiheYoung/UniMatch/assets/84553134/584829de-d950-4ced-a6f0-2490451187ba)

**Comment by LiheYoung** [comment]
1. Supervised baseline denotes only using labeled images for training, without unlabeled images.
2. Pascal VOC contains 1464 high-quality labeled images and other 9118 low-quality labeled images. The "Full" here denotes using 1464 labeled images, and treating other 9118 images as unlabeled ones.

**Comment by tanveer6715** [comment]
> 1. Supervised baseline denotes only using labeled images for training, without unlabeled images.
> 2. Pascal VOC contains 1464 high-quality labeled images and other 9118 low-quality labeled images. The "Full" here denotes using 1464 labeled images, and treating other 9118 images as unlabeled ones.

Thank you for your quick response. It is clear now that semi supervised method showed better performance by utilizing the rest of unlabeled images in the dataset as compare to the supervised method. Can this method be used as unsupervised learning approach if we do not provide any label image so the label list of the dataset will be empty? is it possible?

**Comment by LiheYoung** [comment]
I think it is not possible, because our method requires a trained segmentation model to produce pseudo labels on unlabeled images.

**Comment by tanveer6715** [comment]
> I think it is not possible, because our method requires a trained segmentation model to produce pseudo labels on unlabeled images.

Thank you for your help. I am closing this issue.
