### ISSUE TITLE
training_logs中的log文件名字前的数字含义

### ISSUE THREAD

**Issue by TuBG** [LiheYoung/UniMatch#43]
您好，请问一下training_logs中的log文件名字前的数字代表什么含义呢？例如training-logs/Pascal-VOC-2012/High-Quality-Split-Size321/ResNet-101/下的1464-run1.log、183-run1.log、366-run1.log中的1464,183,366。

**Comment by LiheYoung** [comment]
你好，正如我们表格head中所示，183, 366, 1464这些表示labeled images的数量。

**Comment by TuBG** [comment]
好的，感谢您的回答!
