### ISSUE TITLE
Qestions about weak augmentation on raw image

### ISSUE THREAD

**Issue by Esther-PAN** [LiheYoung/UniMatch#44]
Hello, your work has inspired me a lot! But I have a question about weak augumentation on raw image. The paper mentions applying weak perturbations such as crop and flip to the input images at the image level. However, I couldn't find the specific code for these perturbations. Could you please let me know which perturbations were applied and provide the relevant code if possible? Thank you very much!

**Comment by LiheYoung** [comment]
Hi, the code is here:
https://github.com/LiheYoung/UniMatch/blob/583e32492b0ac150e0946b65864d2dcc642220b8/dataset/semi.py#L41-L44

**Comment by Esther-PAN** [comment]
Thank you for your enthusiastic response ~
