### ISSUE TITLE
请问怎么理解图像级干扰和特征级干扰应该分成单独的流？

### ISSUE THREAD

**Issue by TuBG** [LiheYoung/UniMatch#45]
1. unimatch结构中的辅助干扰流不也是图像级干扰和特征级干扰的混合吗？原始图像xu经过图像级弱干扰变成xw，然后输入编码器g，接着对生成的ew特征进行drop out干扰，这不是图像级干扰和特征级干扰的混合吗？
2. 论文中第7页左下角原话“we inject the dropout on the features of strongly perturbed images”，是指将unimatch中的xs1和xs2经过编码器g输出的特征也进行drop out然后再输入到解码器h中吗？
以上就是我的疑问，期待您的解惑，如果对于论文理解有误的话，还烦您指出并纠正，感谢！

**Comment by LiheYoung** [comment]
1. 正如文章中所讨论的，将图像**强**扰动和特征**强**扰动(Dropout)分离到两个独立的分支进行学习，能够避免单分支过于困难，也可以在每个分支分别学习到相应的扰动不变性。我们认为**弱**扰动不属于图像级别的强扰动，其扰动强度很小，因此特征扰动的分支不会因为图像级别的**弱**扰动而变得困难。
2. 这是我们为了证明在**strongly** perturbed images的features上注入Dropout**不好**而做的ablation study，第7页这句话是对这个反向的ablation study的描述，我们的方法是将Dropout加在了**weakly** perturbed images的features上，正如文章Section3.2斜体强调的那样。

**Comment by TuBG** [comment]
好的，感谢解答！
