### ISSUE TITLE
您好，想请教一下如何进行predict

### ISSUE THREAD

**Issue by PaiDaxing114514** [LiheYoung/UniMatch#46]
大佬您好，我想问一下训练自己的数据集得到了权重之后，如何根据权重进行预测测试集？

**Comment by LiheYoung** [comment]
你好，可以参考这一部分：https://github.com/LiheYoung/UniMatch/blob/583e32492b0ac150e0946b65864d2dcc642220b8/supervised.py#L33

**Comment by 79zzz** [comment]
您好，我看supervised这部分代码中是使用的有标签数据，这部分不是训练集吗
