### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by ChengxiHAN** [LiheYoung/UniMatch#52]
hi, young,

sh scripts/train.sh <num_gpu> <port>

what is port means?  

Is it ture for training? 

sh scripts/train.sh 4 output

**Comment by LiheYoung** [comment]
It is the port for DDP training. You can simply set it as one random number ranging from ``20000`` to ``30000``, e.g., ``20004``.

**Comment by ChengxiHAN** [comment]
Thanks very much, bro!
