### ISSUE TITLE
Experimental results of CPS

### ISSUE THREAD

**Issue by Hugo-cell111** [LiheYoung/UniMatch#53]
Hi! In the paper of Unimatch, the recorded results of CPS on the Cityscapes dataset is 69.8 74.3 74.6 76.8 with ResNet-101 used. But in the original paper of [CPS](https://readpaper.com/paper/4695871168792510465), the results are 74.72 77.62 79.21 80.21 (corresponds to 1/16 1/8 1/4 1/2, respectively). I wonder why there exists an obvious difference?

**Comment by LiheYoung** [comment]
We could not reproduce the reported results of CPS, so we borrow the reported CPS results from U2PL. You may also refer to https://github.com/LiheYoung/ST-PlusPlus/issues/15 and https://github.com/charlesCXK/TorchSemiSeg/issues/43 for details.

**Comment by Hugo-cell111** [comment]
Thanks! By the way, do you know what are the differences between the original implementation and the reproduction? How can the performance be so good in CPS, while the performance drops rapidly after reproducing?

**Comment by LiheYoung** [comment]
Sorry. I failed to figure it out. The reproduced results are indeed from U2PL. It seems U2PL does not provide the reproduced CPS code. If you have any ideas, you can also share them here. :)

**Comment by Hugo-cell111** [comment]
Get it. Thank you!
