### ISSUE TITLE
Question about the training of fixmatch

### ISSUE THREAD

**Issue by yasuobinggan** [LiheYoung/UniMatch#54]
Hello, I experimented with unimatch and fixmatch separately under the condition "VOC2012 92labeled-GPU 4*3090". The code is not adjusted.
I found that the training of unimatch is stable and can achieve very good performance, but the training of fixmatch is very unstable and fails to show a state of gradual convergence after climbing.

The validation set curve:
The blue line is unimatch
The yellow line is fixmatch

I would like to ask the instability of fixmatch is normal? Do you have any relevant solutions?
Thank you so much!
![image](https://github.com/LiheYoung/UniMatch/assets/30293157/9eb55534-38d3-4e9a-85c4-54c23661d427)

**Comment by LiheYoung** [comment]
According to the curve, it seems you tried the ``92`` labeled setting. Due to the extremely scarce label, I think such instability is acceptable for FixMatch. If I remember correctly, other settings with more labeled images will be much better and more stable, such as ``732`` and ``1464``.

**Comment by yasuobinggan** [comment]
Get it, thank you!
