### ISSUE TITLE
Can UniMatch be used for Domain Adaptation?

### ISSUE THREAD

**Issue by mr-intj-22** [LiheYoung/UniMatch#55]
Hi Young, great work!

I was wondering if this method can perform well for the Domain Adaptation task. I have a dataset (street driving domain) that is unlabelled and would like to include it in the unlabelled dataset. While the labeled dataset would be something like cityscapes, and maybe, other labeled datasets like (KITTI, GTA, BDD100K, etc).

Any suggestions? would it work?

**Comment by LiheYoung** [comment]
Hi, of course. I have also made some attempts on UniMatch for domain adaptation. It can work.

One key modification is that you should CutMix labeled (source domain) and unlabeled (target domain) images in domain adaptation, rather than mixing among unlabeled images in semi-supervised learning.

**Comment by mr-intj-22** [comment]
I see that's great! do you have any results from the Domain adaptation experiment?

I understand, so should the (source domain) image be also strongly perturbed? or the weakly perturbed one is enough to CutMix?

another point is, should the (source domain) image be CutMix-ed into the (target domain) image or the opposite? I assume the (target domain) image pixels should dominate the image but I would like some insights if possible.

**Comment by LiheYoung** [comment]
Sorry that I cannot remember the results clearly.

But I remember the much better choice is to paste a rectangle region of the source-domain labeled image onto the target-domain image. The target-domain region should be larger and dominate the learning because our final test domain is the target domain. The source-domain image is CutMixed onto the target-domain image just to narrow the domain gap.

And the weakly perturbed source-domain image is enough for CutMix, because it uses human labels as the supervision. To some extent, human supervision itself can serve as a perturbation for our model. Also, strong perturbations will also possibly damage its original source-domain property.

**Comment by mr-intj-22** [comment]
Thank you a lot! I will sure let you know how it goes!

**Comment by LiheYoung** [comment]
I am going to close this issue now. If you obtain the results, you can re-open it and share them here! Thank you. :)

**Comment by tanveer6715** [comment]
> Thank you a lot! I will sure let you know how it goes!

Hi,
Have you try domain adoption and obtained the results. If so then please share your experience how it works. Thanks

**Comment by mr-intj-22** [comment]
@tanveer6715 Unfortunately, my hardware didn't allow me to train. I managed to get mIoU=0.72 on cityscapes using the 1/16 split with a smaller image size of 640 and a batch of 2 images only to accumulate the hardware limitations. We'll try to get better hardware and try.

**Comment by tanveer6715** [comment]
> @tanveer6715 Unfortunately, my hardware didn't allow me to train. I managed to get mIoU=0.72 on cityscapes using the 1/16 split with a smaller image size of 640 and a batch of 2 images only to accumulate the hardware limitations. We'll try to get better hardware and try.

@mr-intj-22  ok thanks. But would you share what kind of changes you made for domain adaptation using UniMatch?

**Comment by tanveer6715** [comment]
> Hi, of course. I have also made some attempts on UniMatch for domain adaptation. It can work.
> 
> One key modification is that you should CutMix labeled (source domain) and unlabeled (target domain) images in domain adaptation, rather than mixing among unlabeled images in semi-supervised learning.

@LiheYoung I am using UniMatch for domain adaptation according to your above suggestions. But I am facing problems and errors.
1. As you said we should cutmix labeled data (source domain) on unlabeled dataset (target domain) but I didnt understand it should be done before training or during training. In the UniMatch, from the unlabeled data cutmix box is obtained here.
 https://github.com/LiheYoung/UniMatch/blob/583e32492b0ac150e0946b65864d2dcc642220b8/dataset/semi.py#L49
 
 2. Then during the training the unlabeled is cutmixed here. Will you guide how to obtain cutmix from label data and cutmixed with unlabeled data as in semisupervised learning label and unlabeled data is processed and trained separately. Will it be done before or during the training. Also cutmixed of unlabeled data on the unlabeled data as UniMatch can affect the model performance for domain adaptation.
https://github.com/LiheYoung/UniMatch/blob/583e32492b0ac150e0946b65864d2dcc642220b8/unimatch.py#L142
