### ISSUE TITLE
About GPUs

### ISSUE THREAD

**Issue by ChengxiHAN** [LiheYoung/UniMatch#56]
Hi, bro
How can I start my training for Number 2 and 3 GPU not from starting Number 0 GPU, if I set the <num_gpu> of 2. I know the program is starting from the default GPU '0'. 

Many thanks.
Sigma

**Comment by LiheYoung** [comment]
Add environment variable``CUDA_VISIBLE_DEVICES=2,3`` before your command, such as:
```
CUDA_VISIBLE_DEVICES=2,3 sh scripts/train.sh 2 20024
```

**Comment by ChengxiHAN** [comment]
many thanks bro! Can I add your wechat bro ?  (My wechat is: whuhanchengxi)

**Comment by LiheYoung** [comment]
Okay.
