### ISSUE TITLE
Query regarding results on Pascal VOC Blended dataset

### ISSUE THREAD

**Issue by Srinivasa-Divakar-Bhat** [LiheYoung/UniMatch#61]
Hi,
Thank you for actively responding to the queries. 
I noticed from the training logs provided for PASCAL VOC blended dataset for 1/4 split the following results,
run_1 77.54
run_2 77.21
run_3 77.44
But the reported result in the paper is 77.2. Is there any specific reason for doing so? Also can you please shed some light on how stochastic are the results? What possibly could be the range?
Thanks in advance.

**Comment by LiheYoung** [comment]
The reported 77.2 result comes from our very initial experiment. But we lost its corresponding log. Then, we re-run the code three times for providing logs, and obtain the three results you show: 77.54, 77.21, and 77.44. We respect our initial experiment and still report the 77.2 result.

As for the stochastic range, I think it may be within 0.6% mIoU.
