### ISSUE TITLE
关于在遥感数据集LEVIR-CD上的指标问题

### ISSUE THREAD

**Issue by halooy** [LiheYoung/UniMatch#62]
您好
很感谢做出的工作
我想请问一下在遥感数据集LEVIR-CD上，当标记率上升到40%时，为什么两项指标反而下降了呢？
期待您的回复！

**Comment by LiheYoung** [comment]
你好，感谢关注。

我个人觉得是因为随机性，在40% label上我之后也跑出来过比20%更高的结果，但还是尊重了第一次跑实验得到的这个略低的数据，选择了报告这个数据。
