### ISSUE TITLE
关于分类器的疑问

### ISSUE THREAD

**Issue by Hugo-cell111** [LiheYoung/UniMatch#67]
你好！我发现很多半监督语义分割的工作的classifier网络架构是不同的，比如ICLR2022的ReCO，它的分类器是把映射后的c1和经过ASPP的c4拼接起来，然后过两层卷积层，但是你们的分类器是过了三层卷积层。再如CVPR2022的U2PL，他们没有像你们和U2PL一样把c1的channel从256减到48，而是直接进行project，分类器卷积层的channel数就从304变成了512. 我想问一下大家的工作的分类器都不太一样，得到的结果能够进行公平的对比吗？谢谢！
以下是代码链接，刚好对应了三份工作关于classifer的定义部分：[U2PL](https://github.com/Haochen-Wang409/U2PL/blob/ab3d2be313d4d6b2885e7a0213d4fce82a803b79/u2pl/models/decoder.py#L82)，[ReCO](https://github.com/lorenmt/reco/blob/main/network/deeplabv3/deeplabv3.py#L36)和你们的[UniMatch](https://github.com/LiheYoung/UniMatch/blob/main/model/semseg/deeplabv3plus.py#L29)

**Comment by LiheYoung** [comment]
你好，我们follow了比较常见的DeepLabV3Plus的实现，和ReCo的两层 vs. 三层卷积的区别应该没什么影响；此外，我们有具体对比过U2PL的DeepLabV3Plus和我们的结构，结果非常接近，基本没有影响。
