### ISSUE TITLE
Questions about the training code

### ISSUE THREAD

**Issue by mai556** [LiheYoung/UniMatch#68]
![image](https://github.com/LiheYoung/UniMatch/assets/50618245/94d01469-f127-47a6-b8b0-4b52696f38e6)
As shown, I'm wondering why img_u_w_mix is processed in `model.eval()` mode while img_u_w is processed in `model.train()` mode. Is this in any special consideration?

Thank you！

**Comment by LiheYoung** [comment]
The ``img_u_w`` is to provide clean and informative BN statistics to the model, therefore we set ``model.train()``. The ``model.eval()`` mode for ``img_u_w_mix`` is indeed not a necessity. You can even directly CutMix ``img_u_w`` and ``img_u_w.flip(0)``.

**Comment by mai556** [comment]
Thank you! I find that the BN is very magical in semi-supervised tasks.
