### ISSUE TITLE
请教代码中的cutmix_box含义

### ISSUE THREAD

**Issue by wenxin-zhao** [LiheYoung/UniMatch#69]
可以请教一下obtain_cutmix_box得到的cutmix_box1的作用吗？

**Comment by LiheYoung** [comment]
cutmix_box中有0和1两个值，为1的区域是一个矩形区域，可以根据这个区域来mix两张图像，例如：
https://github.com/LiheYoung/UniMatch/blob/583e32492b0ac150e0946b65864d2dcc642220b8/unimatch.py#L142-L145

**Comment by wenxin-zhao** [comment]
非常感谢您的回复，有一个比较困扰我的点希望能得到老师您的指导，就是这种Image-Level Perturbation针对每种数据集都是一样的吗？不知道老师您有做过这方面的实验没？甚至会不会针对每张图片都有自己最合适的Image-Level Perturbation呢？想请教一下老师的看法

**Comment by LiheYoung** [comment]
我们在所有数据集里都用了同样的image-level perturbation；当然，你可以探索每张图像都寻找一个更优的perturbation。

**Comment by LiheYoung** [comment]
Closed for inactivity.
