### ISSUE TITLE
关于特征扰动

### ISSUE THREAD

**Issue by yang654123** [LiheYoung/UniMatch#7]
你好，作者，请问特征扰动的具体代码是哪里呢，我没有找见，可以帮忙标注一下么，谢谢！

**Comment by LiheYoung** [comment]
请参考：
https://github.com/LiheYoung/UniMatch/blob/7292bace1bda8f64ca05ae42ca8c0eef045aa392/model/semseg/deeplabv3plus.py#L45-L51
