### ISSUE TITLE
question about "Prioritizing the selection of labeled images from the high-quality set."

### ISSUE THREAD

**Issue by zhk779** [LiheYoung/UniMatch#70]
![image](https://github.com/LiheYoung/UniMatch/assets/16199731/d1128217-ccf4-40b1-bd0a-a587773c6ec8)
In Table 3, some results are achieved through the application of the strategy "Prioritizing the selection of labeled images from the high-quality set." However, I have not identified this specific "method" or "split" within the provided code. Could you kindly extend your guidance? Much appreciation.

**Comment by LiheYoung** [comment]
This does not modify the method, but only selects a higher-quality part of labeled images from Pascal. The corresponding splits start with 'u2pl', such as: https://github.com/LiheYoung/UniMatch/tree/main/splits/pascal/u2pl_1_16

**Comment by zhk779** [comment]
OK， thanks for your apply

**Comment by zhk779** [comment]
OK， thanks for your apply

> This does not modify the method, but only selects a higher-quality part of labeled images from Pascal. The corresponding splits start with 'u2pl', such as: https://github.com/LiheYoung/UniMatch/tree/main/splits/pascal/u2pl_1_16

OK， thanks for your apply

**Comment by zhk779** [comment]
> This does not modify the method, but only selects a higher-quality part of labeled images from Pascal. The corresponding splits start with 'u2pl', such as: https://github.com/LiheYoung/UniMatch/tree/main/splits/pascal/u2pl_1_16

OK， thanks for your reply！
