### ISSUE TITLE
How to use my own dataset on this implementation?

### ISSUE THREAD

**Issue by archmelow** [LiheYoung/UniMatch#72]
Hello, sir.
I would like to use my own dataset which consists of 100 grayscale images + binary masks (labeled) and 900 unlabeled grayscale images.
Is there a way to use my own dataset other than the datasets which are provided in the instructions?

**Comment by LiheYoung** [comment]
You need to write a new dataset similar to https://github.com/LiheYoung/UniMatch/blob/main/dataset/semi.py

**Comment by archmelow** [comment]
May I ask you one more question?
in semi.py, why would we have to prepare mask files for the unlabeled data? Can I just prepare the img file for the unlabeled Dataset?
Again, thank you for your implementation.

**Comment by LiheYoung** [comment]
Sure. Please refer to this issue: https://github.com/LiheYoung/UniMatch/issues/33#issuecomment-1653531541
