### ISSUE TITLE
Have you conducted experiments using UniMatch for classification?

### ISSUE THREAD

**Issue by Liuzt1999** [LiheYoung/UniMatch#73]
I think UniMatch is a very innovative approach that builds upon FixMatch with some seemingly simple but actually very effective innovations. However, while FixMatch is a classification method, UniMatch is a segmentation method. I'm curious to know if UniMatch performs equally outstandingly in classification tasks.

**Comment by LiheYoung** [comment]
Sorry, I haven't tried this.

**Comment by LiheYoung** [comment]
Closed for inactivity.
