### ISSUE TITLE
The setting of DDP

### ISSUE THREAD

**Issue by Hugo-cell111** [LiheYoung/UniMatch#74]
Hi! I find that the parameter "broadcast_buffer" is set as False, does it matter if it is set as True?

**Comment by LiheYoung** [comment]
It won't matter if you use more than 1 GPU for training. Otherwise, if you use only one GPU and set the ``broadcast_buffer`` as True, you will encounter errors.

**Comment by Hugo-cell111** [comment]
Thanks!
