### ISSUE TITLE
The problem of multi-process distributed training

### ISSUE THREAD

**Issue by Secret813** [LiheYoung/UniMatch#78]
Hello, I would like to know whether your project can be changed to the ordinary single-machine training mode, if so, how to achieve the specific operation?And can one GPU complete the training?

**Comment by LiheYoung** [comment]
Our default script is just for single-machine training:
```bash
sh scripts/train.sh <num_gpu> <port>
```

If you want to use one GPU, set ``<num_gpu>`` as 1. But the performance may be affected.

**Comment by Secret813** [comment]
sh scripts/train.sh <num_gpu> <port>
请问这里的<port>不用输入确定的端口吗

**Comment by LiheYoung** [comment]
The port is also required. For example:
```bash
sh scripts/train.sh 1 20023
```

**Comment by Secret813** [comment]
非常感谢！端口号是可以随机设置的对吧

**Comment by LiheYoung** [comment]
是的，一般在20000-30000间即可
