### ISSUE TITLE
use of unlabelled data

### ISSUE THREAD

**Issue by kushiluv** [LiheYoung/UniMatch#79]
Hey, i am a complete beginner but i'm trying to run your model in my own dataset which has a lot of unlabelled data. From my understanding the point of SSL algos is when you have a lot of unlabelled data which can also be used. But for the model to work I need to place the masks as well in unlabeled.txt (maybe it is being used to evaluate) , is there a way around it?

**Comment by Liumomo30** [comment]
Hello, I have the same issue. Have you resolved it?

**Comment by 79zzz** [comment]
你们指的是无标签数据的掩码吗？
