### ISSUE TITLE
医学图像分割，只有一个类别，阈值那里的softmax该如何修改？

### ISSUE THREAD

**Issue by Linzsd** [LiheYoung/UniMatch#80]
本来是用sigmoid的，但直接将softmax改成sigmoid好像训练不起来，感觉是错误的，求指教

**Comment by LiheYoung** [comment]
如果只有一个类别用softmax，需要模型输出两个通道表示前景和背景这两个类别，loss function（CELoss）和阈值（0.95）都和UniMatch里一样设置就行。

**Comment by Linzsd** [comment]
> 如果只有一个类别用softmax，需要模型输出两个通道表示前景和背景这两个类别，loss function（CELoss）和阈值（0.95）都和UniMatch里一样设置就行。

为什么我这样训练效果不好，在测试集上效果还不如监督训练，我的设置：Lu也用了bce+dice，模型是efficientnet-b5为backbone的Unet，加载预训练权重。
数据集，有标签样本900，无标签2100

**Comment by LiheYoung** [comment]
抱歉，从这些信息很难判断

**Comment by LiheYoung** [comment]
Closed for long inactivity.
