### ISSUE TITLE
For domain adaptation

### ISSUE THREAD

**Issue by tanveer6715** [LiheYoung/UniMatch#82]
> You can check this paper first: https://github.com/vikolss/DACS, for the methodology of mixing labeled and unlabeled images.
> 
> Briefly, we previously mix `img_u_s` and `img_u_s_mix`, right? Now you need to mix `img_u_s` and `img_x` instead. The `img_u_s_mix` and `img_u_w_mix` are no longer required. As for the pseudo label of mixed `img_u_s` and `img_x`, its unlabeled region is predicted on `img_u_w` by our model, and the labeled region directly borrows GT label from `mask_x`.

Hi, 
Sorry I am opening the same issue again #71. I have make changes for the domain adaptation but it still have some errors and the model stop training after some iteration in first epoch. I am showing you the details of changes which I have done for domain adaptation.

1. I have remove img_u_w_mix from data loader as it was no longer required.
![image](https://github.com/LiheYoung/UniMatch/assets/84553134/4dbe336c-21a8-4b6f-9be7-c35f2fc99c71)
2. I have cutmix the img_x which is the source domain with the target domain img_u_s1 and img_u_s2. I also remove the prediction on img_u_w_mix.
![image](https://github.com/LiheYoung/UniMatch/assets/84553134/ea79f0a0-d5ee-4ffb-bf45-5209e68b6f1b)
3. As you have mentioning that the pseudolabel of mix image of img_x and img_s is predicted on img_u_w and its label region is directly from GT label then I make changes accordingly. 
![image](https://github.com/LiheYoung/UniMatch/assets/84553134/f1d1f3e8-cd4e-497a-b42e-1758c0ebf532)
Please have a look to these changes and suggest any further changes or point out any mistakes which I have done for domain adaptation. Thanks

**Comment by LiheYoung** [comment]
There is at least one mistake: you should use ``cutmix_box1`` and ``cutmix_box2`` to mix unlabeled target-domain images and labeled source-domain images, rather than use ``cutmix_box0``.

**Comment by tanveer6715** [comment]
yeah sorry it was a typo mistake. I did the same use the cutmix box1 and cutmix box 2 but when I start training it shows error after some iteration in 1st epoch. Also cutmix box1 and 2 is obtained from unlabeled images right and it get pasted on label images?
![image](https://github.com/LiheYoung/UniMatch/assets/84553134/a15b2ac8-ac18-4b07-a919-0b96d08f3b10)

**Comment by tanveer6715** [comment]
> yeah sorry it was a typo mistake. I did the same use the cutmix box1 and cutmix box 2 but when I start training it shows error after some iteration in 1st epoch. Also cutmix box1 and 2 is obtained from unlabeled images right and it get pasted on label images? ![image](https://user-images.githubusercontent.com/84553134/268488314-a15b2ac8-ac18-4b07-a919-0b96d08f3b10.png)

I have resolved this problem but surprisingly the performance of the model is still same after these changes. Would you recommend any further changes? Did you use same loss functions for domain adaptation?

**Comment by LiheYoung** [comment]
Yes. I used the same loss functions. But sorry I cannot remember every details.

**Comment by tanveer6715** [comment]
ok thank you. I am closing this issue.
