### ISSUE TITLE
关于代码和分布式并行运行的问题

### ISSUE THREAD

**Issue by DaD3zZ** [LiheYoung/UniMatch#85]
最近在追您的工作，想做一些实验，目前遇到了几个问题，麻烦您帮忙看一下：

1.由于我的环境是单卡的集群，在按照readme里配置后，使用这个指令运行，出现下面的问题，请问您是否遇见过，有没有什么建议？
sh scripts/train.sh 1 20023
<img width="1145" alt="image" src="https://github.com/LiheYoung/UniMatch/assets/27292019/596cccb4-411b-4e48-9cb5-b8f2083fb27f">

2.还有个思路上的问题，我看到您的代码中，包括特征级的扰动，和图像级的强扰动，都是采用同样的参数来实施的，那么您是否考虑过对于每个图片，采用更随机的参数来进行各种扰动？

**Comment by LiheYoung** [comment]
1. 安装six库
2. 我们没有尝试过

**Comment by DaD3zZ** [comment]
在你们的dataloader中，没有设置shuffle=True，那么是否每个epoch都是按照原始的顺序来训练的，这样不应该可能比shuffle一下的效果略差一点吗？
<img width="760" alt="image" src="https://github.com/LiheYoung/UniMatch/assets/27292019/cea7af99-803e-4e0d-9fc1-7c2dd44342c3">
同时，在每个epoch中，是否你们的img_u_w和img_u_w_mix等，也是是同一个batch的图片的不同裁剪，那这样后续进行cutmix时，是否也是同一张图的区域进行拼接？这样的话会不会扰动的效果不够好？在我的理解里两个不同的batch之间相互裁剪的扰动更高？
<img width="748" alt="image" src="https://github.com/LiheYoung/UniMatch/assets/27292019/c7149fa8-0bd4-40d7-92b0-16992eef4e27">
请问你们有没有试过上述的变化？或者你们是怎么考虑这个问题的？

**Comment by DaD3zZ** [comment]
或者说，您们在数据处理时，因为是对原图的随机剪裁，所以对于两个问题都默认了即使都是从同一张原图上剪裁的，但是也是不一样的两张图

**Comment by LiheYoung** [comment]
1. 每个epoch开始时设置了trainloader.sampler.set_epoch(epoch)，会改变sampling的顺序
2. ``img_u_w``和``img_u_w_mix``确实是来自一张图像的不同crop，这不是我们有意为之，更正确的方式是用不同的图像进行CutMix，但我们尝试之后发现和现在的做法性能几乎没有区别

**Comment by DaD3zZ** [comment]
好的，非常感谢您的回复，但是由于我一直使用单卡的方式来训练的，所以删掉了那一行，所以我会感觉每一个epoch采样的顺序没有变。
所以我只需要在dataloader中设置shuffle=True就可以了

我尝试将您的工作用在UDA任务上进行了少量的实验，参考您之前#71个issue的回复，我是这样采取的设置：
以下我将用Xs代表源域有标签数据（GTA5），Xut代表目标域无标签数据（Cityscapes）
1.Xs进行有监督训练
2.Xut进行弱扰动并输入，产生一个弱扰动分支和一个特征扰动分支
3.用Xut的强扰动 cutmix 上Xs的弱扰动图像 部分区域，构造两个强扰动流

但是很不幸，这样的设置训练的效果特别差，可能MeanIoU大概在30多，经过了我加上一些UDA的方法后也只能勉强达到40多。在#71问题中提到，你们曾经做过一定的实验并且it works，请问您能给我点建议吗？

**Comment by LiheYoung** [comment]
有可能是BN处理的不对，可以先按照[DACS](https://github.com/vikolss/DACS)实现一个基础的FixMatch版本，然后再将单支的strong aug改为双支，以及再加入feature aug。

**Comment by DaD3zZ** [comment]
好的，非常感谢您！

**Comment by yyamx** [comment]
Traceback (most recent call last):
  File "unimatch.py", line 250, in <module>
    main()
  File "unimatch.py", line 53, in main
    model = DeepLabV3Plus(cfg)
  File "/root/autodl-tmp/model/semseg/deeplabv3plus.py", line 14, in __init__
    self.backbone = resnet.__dict__[cfg['backbone']](pretrained=True, 
  File "/root/autodl-tmp/model/backbone/resnet.py", line 163, in resnet101
    return _resnet('resnet101', Bottleneck, [3, 4, 23, 3], pretrained, **kwargs)
  File "/root/autodl-tmp/model/backbone/resnet.py", line 153, in _resnet
    state_dict = torch.load(pretrained_path)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/serialization.py", line 749, in _legacy_load
    return legacy_load(f)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/serialization.py", line 678, in legacy_load
    args = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x03'.这个问题是什么情况呢

**Comment by DaD3zZ** [comment]
非常感谢您提的建议，但是请问您是否记得，当时您作DA任务的时候，是采用DACS方法中的classMix作为一股强扰动分支，还是只是使用classMix构造一个混合域，再用混合域进行进一步的强扰动？

**Comment by LiheYoung** [comment]
我们当时用的应该也是CutMix，做法跟UniMatch在半监督中类似，即用CutMix混合**strongly augmented** target&source-domain images.

**Comment by GVJHK** [comment]
> 最近在追您的工作，想做一些实验，目前遇到了几个问题，麻烦您帮忙看一下：
> 
> 1.由于我的环境是单卡的集群，在按照readme里配置后，使用这个指令运行，出现下面的问题，请问您是否遇见过，有没有什么建议？ sh scripts/train.sh 1 20023 <img alt="image" width="1145" src="https://user-images.githubusercontent.com/27292019/270171125-596cccb4-411b-4e48-9cb5-b8f2083fb27f.png">
> 
> 2.还有个思路上的问题，我看到您的代码中，包括特征级的扰动，和图像级的强扰动，都是采用同样的参数来实施的，那么您是否考虑过对于每个图片，采用更随机的参数来进行各种扰动？

你好，请问单卡单gpu运行readme指令时会显示<附近有语法错误是怎么回事，你有在train.sh中进行一些修改吗？可否请教您一下。

**Comment by GVJHK** [comment]
> 最近在追您的工作，想做一些实验，目前遇到了几个问题，麻烦您帮忙看一下：
> 
> 1.由于我的环境是单卡的集群，在按照readme里配置后，使用这个指令运行，出现下面的问题，请问您是否遇见过，有没有什么建议？ sh scripts/train.sh 1 20023 <img alt="image" width="1145" src="https://user-images.githubusercontent.com/27292019/270171125-596cccb4-411b-4e48-9cb5-b8f2083fb27f.png">
> 
> 2.还有个思路上的问题，我看到您的代码中，包括特征级的扰动，和图像级的强扰动，都是采用同样的参数来实施的，那么您是否考虑过对于每个图片，采用更随机的参数来进行各种扰动？

我跟您一样的错误，six库也安装了还是这样，不知道您是怎么解决的呢？

**Comment by yyamx** [comment]
> > 最近在追您的工作，想做一些实验，目前遇到了几个问题，麻烦您帮忙看一下：
> > 1.由于我的环境是单卡的集群，在按照readme里配置后，使用这个指令运行，出现下面的问题，请问您是否遇见过，有没有什么建议？ sh scripts/train.sh 1 20023 <img alt="image" width="1145" src="https://user-images.githubusercontent.com/27292019/270171125-596cccb4-411b-4e48-9cb5-b8f2083fb27f.png">
> > 2.还有个思路上的问题，我看到您的代码中，包括特征级的扰动，和图像级的强扰动，都是采用同样的参数来实施的，那么您是否考虑过对于每个图片，采用更随机的参数来进行各种扰动？
> 
> 我跟您一样的错误，six库也安装了还是这样，不知道您是怎么解决的呢？

我也遇到这个问题了请问解决了吗

**Comment by DaD3zZ** [comment]
我那个问题后来解决了，应该是我服务器的容器自身配置有问题，配置过之前别的环境版本，我重建容器后重配了环境就好了
当时我是装不上six库，你这种情况可能还得针对six库安装后再看看

**Comment by GVJHK** [comment]
谢谢您的解答，我那个可以装上six库，但我是单卡，应该是并行运行的问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiheYoung/UniMatch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月15日(星期三) 中午11:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LiheYoung/UniMatch] 关于代码和分布式并行运行的问题 (Issue #85)





 
我那个问题后来解决了，应该是我服务器的容器自身配置优点问题，我重建容器后重配了环境就好了
 当时我是装不上six库，你这种情况可能还得针对six库安装后再看看

**Comment by tanveer6715** [comment]
> Okay, thank you very much for your reply, but since I have been training using a single card, I deleted that line, so I feel that the order of sampling in each epoch has not changed. So I just need to set shuffle=True in the dataloader.
> 
> I tried to apply your work to the UDA task and conducted a small amount of experiments. Referring to your previous reply to issue #71, I adopted the following settings: Below I will use Xs to represent the source domain with labeled data (GTA5), Xut Represents the unlabeled data in the target domain (Cityscapes) 1. Xs performs supervised training 2. Xut performs weak perturbation and inputs it, generating a weak perturbation branch and a feature perturbation branch 3. Use Xut's strong perturbation cutmix on the weak perturbation image part of Xs area, constructing two strong disturbance flows
> 
> But unfortunately, the training effect of this setting is very poor. Maybe the MeanIoU is about 30, and after I added some UDA methods, it can only barely reach 40. As mentioned in question #71, you have done some experiments and it works. Can you give me some advice?

Have you tried domain adaptation using UniMatch? Can you share your experience and results?
