### ISSUE TITLE
Problems with custom dataset

### ISSUE THREAD

**Issue by adesfoss** [LiheYoung/UniMatch#88]
Hello, I'm working with your project in change detection (more-scenarios/remote-sensing/) with a custom dataset (images are in .tif file format so I adapted the code). For some reason, when I try the code with the LEVIR dataset everything works as expected but if I use my custom dataset, It doesn't detect any changes. (100% unchanged). I've thoroughly debugged with both dataset to compare values of variables at specific points and there's nothing weird happening. I know that my dataset has a lower density of changes compared to LEVIR.

Would you any idea or suggestions as to why that's the case ? Thank you

**Comment by LiheYoung** [comment]
You may need better loss functions to deal with the severe class imbalance issue, *e.g*., the dice loss.
