### ISSUE TITLE
二分类数据集训练精度不变

### ISSUE THREAD

**Issue by ZHIZIHUABU** [LiheYoung/UniMatch#89]
我在自己的数据集上进行训练，数据集为二分类，判断是否合格，其中我选取合格和不合格的图片各45张，合格图label全为0，不合格图只有缺陷区域label为1，背景为0（缺陷面积占比较小），验证时iou不变，我有两个疑问：
1、自建数据集，label是单通道图，二分类值为0,1，而voc数据集则用彩色绘制类别，这样会有问题吗？
2、在我的二分类数据集上，即便是不合格图，背景区域占据主要部分，且label=0，这样会导致模型prediction向0预测吗
![Uploading Snipaste_2023-10-25_13-39-19.png…]()

**Comment by ZHIZIHUABU** [comment]
![Uploading Snipaste_2023-10-25_13-39-19.png…]()

**Comment by LiheYoung** [comment]
类别不平衡的问题太严重了，应该需要其他更合适的损失函数，比如dice loss或者IoU loss。
