### ISSUE TITLE
Pretrained Backbone issue

### ISSUE THREAD

**Issue by cjf8899** [LiheYoung/UniMatch#9]
hello! Thanks for the good research!

I tried to use resnet-50,101, but I can't download it with a link that exists in Pretrained Backbone.

please check! :pray: thank you!

**Comment by LiheYoung** [comment]
Hi, thank you for pointing it out. The downloading links have been updated. Please have a check.

**Comment by cjf8899** [comment]
Links work great! thank you!! :smiley:
