### ISSUE TITLE
VOC2012 Results

### ISSUE THREAD

**Issue by YUCOCOCS** [LiheYoung/UniMatch#93]
您好，感谢您卓越的工作，我在论文中的表2发现，在ResNet101的基础上，1464(Full)的划分下，能达到81.2的实验性能，但是我仔细查看了您的实验日志，进行了三次重复的实验，结果分别为80.78， 80.71， 81.01。  我对此有些不解，期望得到您的回复。

**Comment by LiheYoung** [comment]
你好，我们论文里Table2报告的结果是很早的时候跑出来的，相当于第一次跑出来的结果，但这些结果的log没有保存好；后面我们为了方便大家复现又在每个划分下重新跑了三次并且提供了logs，所以这边结果因为随机性和实验环境会有一些波动

**Comment by YUCOCOCS** [comment]
好的，感谢您及时的回复~，希望学业顺利
