### ISSUE TITLE
关于强增强图片和弱增强图片的问题

### ISSUE THREAD

**Issue by YUCOCOCS** [LiheYoung/UniMatch#95]
您好，我看现在大多数的半监督语义分割方法都是采用一致性正则化的方式，即用弱增强产生的预测来监督强增强产生的结果，我看文章中说这样做能达到很高的性能，但是至于这样做的原理和好处是什么，我不太能明白，请问你可以为我解答一下嘛？期望您的回复。

**Comment by LiheYoung** [comment]
弱增广的较为干净的图片可以提供更精确的伪标签，而强增广可以让模型学习难度更大，从而获得额外的知识，也能缓解过拟合错误的伪标签。
