### ISSUE TITLE
Question about the evaluation time

### ISSUE THREAD

**Issue by Hugo-cell111** [LiheYoung/UniMatch#96]
Hi! Why the evaluation process in the first epoch cost so much time, while the speed is normal in the following epochs? The log is [here](https://github.com/LiheYoung/UniMatch/blob/main/training-logs/Pascal-VOC-2012/U2PL-Split-Size513/ResNet-101/1_8.log#L33) and [here](https://github.com/LiheYoung/UniMatch/blob/main/training-logs/Pascal-VOC-2012/U2PL-Split-Size513/ResNet-101/1_8.log#L66). In the first epoch, it takes 91s; in the other epochs, it just takes 19-20s. Thanks!

**Comment by LiheYoung** [comment]
I am not sure the reason. It may be related to my used disk. But I think the 90s test time is acceptable.

**Comment by Hugo-cell111** [comment]
No. When I reproduce UniMatch and other variants(such as UniPerb and DusPerb) on my own server, the same problem occurs to, so I think it might not just relate to the disk personally. Anyway, it is not a big problem since after the 2nd epoch everything goes normal. Thank you!
