### ISSUE TITLE
关于分布式训练的问题

### ISSUE THREAD

**Issue by Secret813** [LiheYoung/UniMatch#97]
您好，我想对您的项目做一些实验，在deeplabv3种加入了一个表示模块
`self.representation = nn.Sequential(
            nn.Conv2d(304, 256, 3, padding=1, bias=False),
            nn.BatchNorm2d(256),
            nn.ReLU(),
            nn.Conv2d(256, output_dim, 1)
        )`
这样模型就增加了参数，于是有了报错`RuntimeError: Error(s) in loading state_dict for DistributedDataParallel:
        Missing key(s) in state_dict: "module.representation.0.weight", "module.representation.1.weight", "module.representation.1.bias", "module.representation.1.running_mean", "module.representation.1.running_var", "module.representation.3.weight", "module.representation.3.bias". 
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1010) of binary: /root/miniconda3/bin/python`
我不太了解分布式训练的代码，请问该如何处理这个报错呢？

**Comment by LiheYoung** [comment]
你应该是在load backbone或整个模型的参数的时候报的错，在load的时候加上``strict=False``
